/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FieldTypeDefinition } from '../../models/field-type-definition';

export interface CustomFormsFieldTypesGet$Params {
}

export function customFormsFieldTypesGet(http: HttpClient, rootUrl: string, params?: CustomFormsFieldTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: FieldTypeDefinition;
}>> {
  const rb = new RequestBuilder(rootUrl, customFormsFieldTypesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: FieldTypeDefinition;
      }>;
    })
  );
}

customFormsFieldTypesGet.PATH = '/custom-forms/field-types';
