/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomFormWithBaseAnswerOutput } from '../../models/custom-form-with-base-answer-output';

export interface CustomFormsByMissionTypeMissionTypeIdBaseAnswerGet$Params {
  missionTypeId: string;
}

export function customFormsByMissionTypeMissionTypeIdBaseAnswerGet(http: HttpClient, rootUrl: string, params: CustomFormsByMissionTypeMissionTypeIdBaseAnswerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomFormWithBaseAnswerOutput>>> {
  const rb = new RequestBuilder(rootUrl, customFormsByMissionTypeMissionTypeIdBaseAnswerGet.PATH, 'get');
  if (params) {
    rb.path('missionTypeId', params.missionTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomFormWithBaseAnswerOutput>>;
    })
  );
}

customFormsByMissionTypeMissionTypeIdBaseAnswerGet.PATH = '/custom-forms/by-mission-type/{missionTypeId}/base-answer';
