/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomFormInput } from '../../models/custom-form-input';
import { CustomFormOutput } from '../../models/custom-form-output';

export interface CustomFormsIdPut$Params {
  id: string;
      body?: CustomFormInput
}

export function customFormsIdPut(http: HttpClient, rootUrl: string, params: CustomFormsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormOutput>> {
  const rb = new RequestBuilder(rootUrl, customFormsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomFormOutput>;
    })
  );
}

customFormsIdPut.PATH = '/custom-forms/{id}';
