/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AbsenceTypeOutput } from '../models/absence-type-output';
import { absenceTypesGet } from '../fn/absence-types/absence-types-get';
import { AbsenceTypesGet$Params } from '../fn/absence-types/absence-types-get';
import { absenceTypesIdDelete } from '../fn/absence-types/absence-types-id-delete';
import { AbsenceTypesIdDelete$Params } from '../fn/absence-types/absence-types-id-delete';
import { absenceTypesIdGet } from '../fn/absence-types/absence-types-id-get';
import { AbsenceTypesIdGet$Params } from '../fn/absence-types/absence-types-id-get';
import { absenceTypesIdPut } from '../fn/absence-types/absence-types-id-put';
import { AbsenceTypesIdPut$Params } from '../fn/absence-types/absence-types-id-put';
import { absenceTypesPost } from '../fn/absence-types/absence-types-post';
import { AbsenceTypesPost$Params } from '../fn/absence-types/absence-types-post';

@Injectable({ providedIn: 'root' })
export class AbsenceTypesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `absenceTypesGet()` */
  static readonly AbsenceTypesGetPath = '/absence-types';

  /**
   * Récupérer la liste des types d'absence.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `absenceTypesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  absenceTypesGet$Response(params?: AbsenceTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AbsenceTypeOutput>>> {
    return absenceTypesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des types d'absence.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `absenceTypesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  absenceTypesGet(params?: AbsenceTypesGet$Params, context?: HttpContext): Observable<Array<AbsenceTypeOutput>> {
    return this.absenceTypesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AbsenceTypeOutput>>): Array<AbsenceTypeOutput> => r.body)
    );
  }

  /** Path part for operation `absenceTypesPost()` */
  static readonly AbsenceTypesPostPath = '/absence-types';

  /**
   * Créer un nouveau type d'absence.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `absenceTypesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  absenceTypesPost$Response(params?: AbsenceTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenceTypeOutput>> {
    return absenceTypesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau type d'absence.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `absenceTypesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  absenceTypesPost(params?: AbsenceTypesPost$Params, context?: HttpContext): Observable<AbsenceTypeOutput> {
    return this.absenceTypesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<AbsenceTypeOutput>): AbsenceTypeOutput => r.body)
    );
  }

  /** Path part for operation `absenceTypesIdGet()` */
  static readonly AbsenceTypesIdGetPath = '/absence-types/{id}';

  /**
   * Récupérer les détails d'un type d'absence.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `absenceTypesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  absenceTypesIdGet$Response(params: AbsenceTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenceTypeOutput>> {
    return absenceTypesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'un type d'absence.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `absenceTypesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  absenceTypesIdGet(params: AbsenceTypesIdGet$Params, context?: HttpContext): Observable<AbsenceTypeOutput> {
    return this.absenceTypesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<AbsenceTypeOutput>): AbsenceTypeOutput => r.body)
    );
  }

  /** Path part for operation `absenceTypesIdPut()` */
  static readonly AbsenceTypesIdPutPath = '/absence-types/{id}';

  /**
   * Mettre à jour un type d'absence.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `absenceTypesIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  absenceTypesIdPut$Response(params: AbsenceTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenceTypeOutput>> {
    return absenceTypesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un type d'absence.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `absenceTypesIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  absenceTypesIdPut(params: AbsenceTypesIdPut$Params, context?: HttpContext): Observable<AbsenceTypeOutput> {
    return this.absenceTypesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<AbsenceTypeOutput>): AbsenceTypeOutput => r.body)
    );
  }

  /** Path part for operation `absenceTypesIdDelete()` */
  static readonly AbsenceTypesIdDeletePath = '/absence-types/{id}';

  /**
   * Supprimer un type d'absence.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `absenceTypesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  absenceTypesIdDelete$Response(params: AbsenceTypesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return absenceTypesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un type d'absence.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `absenceTypesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  absenceTypesIdDelete(params: AbsenceTypesIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.absenceTypesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
