/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addressesLocalizeAddressPost } from '../fn/addresses/addresses-localize-address-post';
import { AddressesLocalizeAddressPost$Params } from '../fn/addresses/addresses-localize-address-post';
import { CoordinatesMinimal } from '../models/coordinates-minimal';

@Injectable({ providedIn: 'root' })
export class AddressesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addressesLocalizeAddressPost()` */
  static readonly AddressesLocalizeAddressPostPath = '/addresses/localize-address';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addressesLocalizeAddressPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addressesLocalizeAddressPost$Response(params?: AddressesLocalizeAddressPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CoordinatesMinimal>> {
    return addressesLocalizeAddressPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addressesLocalizeAddressPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addressesLocalizeAddressPost(params?: AddressesLocalizeAddressPost$Params, context?: HttpContext): Observable<CoordinatesMinimal> {
    return this.addressesLocalizeAddressPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<CoordinatesMinimal>): CoordinatesMinimal => r.body)
    );
  }

}
