/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authConfirmEmailGet } from '../fn/auth/auth-confirm-email-get';
import { AuthConfirmEmailGet$Params } from '../fn/auth/auth-confirm-email-get';
import { authForgotPasswordPost } from '../fn/auth/auth-forgot-password-post';
import { AuthForgotPasswordPost$Params } from '../fn/auth/auth-forgot-password-post';
import { authLoginPost } from '../fn/auth/auth-login-post';
import { AuthLoginPost$Params } from '../fn/auth/auth-login-post';
import { authMeGet } from '../fn/auth/auth-me-get';
import { AuthMeGet$Params } from '../fn/auth/auth-me-get';
import { authRefreshTokenPost } from '../fn/auth/auth-refresh-token-post';
import { AuthRefreshTokenPost$Params } from '../fn/auth/auth-refresh-token-post';
import { authRegisterPost } from '../fn/auth/auth-register-post';
import { AuthRegisterPost$Params } from '../fn/auth/auth-register-post';
import { authRequestEmailConfirmationGet } from '../fn/auth/auth-request-email-confirmation-get';
import { AuthRequestEmailConfirmationGet$Params } from '../fn/auth/auth-request-email-confirmation-get';
import { authResetPasswordPost } from '../fn/auth/auth-reset-password-post';
import { AuthResetPasswordPost$Params } from '../fn/auth/auth-reset-password-post';
import { authRevokeTokenPost } from '../fn/auth/auth-revoke-token-post';
import { AuthRevokeTokenPost$Params } from '../fn/auth/auth-revoke-token-post';
import { TokenOutput } from '../models/token-output';
import { UserInfoOutput } from '../models/user-info-output';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authLoginPost()` */
  static readonly AuthLoginPostPath = '/auth/login';

  /**
   * Connexion d'un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authLoginPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authLoginPost$Response(params?: AuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenOutput>> {
    return authLoginPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Connexion d'un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authLoginPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authLoginPost(params?: AuthLoginPost$Params, context?: HttpContext): Observable<TokenOutput> {
    return this.authLoginPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenOutput>): TokenOutput => r.body)
    );
  }

  /** Path part for operation `authRefreshTokenPost()` */
  static readonly AuthRefreshTokenPostPath = '/auth/refresh-token';

  /**
   * Rafraîchir un token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authRefreshTokenPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authRefreshTokenPost$Response(params?: AuthRefreshTokenPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenOutput>> {
    return authRefreshTokenPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Rafraîchir un token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authRefreshTokenPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authRefreshTokenPost(params?: AuthRefreshTokenPost$Params, context?: HttpContext): Observable<TokenOutput> {
    return this.authRefreshTokenPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenOutput>): TokenOutput => r.body)
    );
  }

  /** Path part for operation `authRevokeTokenPost()` */
  static readonly AuthRevokeTokenPostPath = '/auth/revoke-token';

  /**
   * Révoquer un token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authRevokeTokenPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authRevokeTokenPost$Response(params?: AuthRevokeTokenPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authRevokeTokenPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Révoquer un token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authRevokeTokenPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authRevokeTokenPost(params?: AuthRevokeTokenPost$Params, context?: HttpContext): Observable<void> {
    return this.authRevokeTokenPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authRegisterPost()` */
  static readonly AuthRegisterPostPath = '/auth/register';

  /**
   * Inscription d'un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authRegisterPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authRegisterPost$Response(params?: AuthRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Inscription d'un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authRegisterPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authRegisterPost(params?: AuthRegisterPost$Params, context?: HttpContext): Observable<void> {
    return this.authRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authConfirmEmailGet()` */
  static readonly AuthConfirmEmailGetPath = '/auth/confirm-email';

  /**
   * Valider l'adresse e-mail.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authConfirmEmailGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  authConfirmEmailGet$Response(params?: AuthConfirmEmailGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authConfirmEmailGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Valider l'adresse e-mail.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authConfirmEmailGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authConfirmEmailGet(params?: AuthConfirmEmailGet$Params, context?: HttpContext): Observable<void> {
    return this.authConfirmEmailGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authForgotPasswordPost()` */
  static readonly AuthForgotPasswordPostPath = '/auth/forgot-password';

  /**
   * Mot de passe oublié.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authForgotPasswordPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authForgotPasswordPost$Response(params?: AuthForgotPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return authForgotPasswordPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Mot de passe oublié.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authForgotPasswordPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authForgotPasswordPost(params?: AuthForgotPasswordPost$Params, context?: HttpContext): Observable<string> {
    return this.authForgotPasswordPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `authResetPasswordPost()` */
  static readonly AuthResetPasswordPostPath = '/auth/reset-password';

  /**
   * Réinitialiser le mot de passe.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authResetPasswordPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authResetPasswordPost$Response(params?: AuthResetPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authResetPasswordPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Réinitialiser le mot de passe.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authResetPasswordPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authResetPasswordPost(params?: AuthResetPasswordPost$Params, context?: HttpContext): Observable<void> {
    return this.authResetPasswordPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authMeGet()` */
  static readonly AuthMeGetPath = '/auth/me';

  /**
   * Récupérer les informations de l'utilisateur connecté.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authMeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  authMeGet$Response(params?: AuthMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfoOutput>> {
    return authMeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les informations de l'utilisateur connecté.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authMeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authMeGet(params?: AuthMeGet$Params, context?: HttpContext): Observable<UserInfoOutput> {
    return this.authMeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserInfoOutput>): UserInfoOutput => r.body)
    );
  }

  /** Path part for operation `authRequestEmailConfirmationGet()` */
  static readonly AuthRequestEmailConfirmationGetPath = '/auth/request-email-confirmation';

  /**
   * Demander un nouveau lien de confirmation par e-mail.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authRequestEmailConfirmationGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  authRequestEmailConfirmationGet$Response(params?: AuthRequestEmailConfirmationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return authRequestEmailConfirmationGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Demander un nouveau lien de confirmation par e-mail.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authRequestEmailConfirmationGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authRequestEmailConfirmationGet(params?: AuthRequestEmailConfirmationGet$Params, context?: HttpContext): Observable<string> {
    return this.authRequestEmailConfirmationGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
