/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiBogusGenerateAddressesGet } from '../fn/bogus/api-bogus-generate-addresses-get';
import { ApiBogusGenerateAddressesGet$Params } from '../fn/bogus/api-bogus-generate-addresses-get';
import { apiBogusGenerateClientsGet } from '../fn/bogus/api-bogus-generate-clients-get';
import { ApiBogusGenerateClientsGet$Params } from '../fn/bogus/api-bogus-generate-clients-get';
import { apiBogusGenerateDefaultSettingGet } from '../fn/bogus/api-bogus-generate-default-setting-get';
import { ApiBogusGenerateDefaultSettingGet$Params } from '../fn/bogus/api-bogus-generate-default-setting-get';
import { apiBogusGenerateMissionsGet } from '../fn/bogus/api-bogus-generate-missions-get';
import { ApiBogusGenerateMissionsGet$Params } from '../fn/bogus/api-bogus-generate-missions-get';
import { apiBogusGenerateOrdersGet } from '../fn/bogus/api-bogus-generate-orders-get';
import { ApiBogusGenerateOrdersGet$Params } from '../fn/bogus/api-bogus-generate-orders-get';
import { apiBogusGenerateUserAbsenceGet } from '../fn/bogus/api-bogus-generate-user-absence-get';
import { ApiBogusGenerateUserAbsenceGet$Params } from '../fn/bogus/api-bogus-generate-user-absence-get';
import { apiBogusGenerateUsersGet } from '../fn/bogus/api-bogus-generate-users-get';
import { ApiBogusGenerateUsersGet$Params } from '../fn/bogus/api-bogus-generate-users-get';

@Injectable({ providedIn: 'root' })
export class BogusService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiBogusGenerateUsersGet()` */
  static readonly ApiBogusGenerateUsersGetPath = '/api/bogus/generateUsers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateUsersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateUsersGet$Response(params?: ApiBogusGenerateUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateUsersGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateUsersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateUsersGet(params?: ApiBogusGenerateUsersGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateUsersGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiBogusGenerateAddressesGet()` */
  static readonly ApiBogusGenerateAddressesGetPath = '/api/bogus/generateAddresses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateAddressesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateAddressesGet$Response(params?: ApiBogusGenerateAddressesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateAddressesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateAddressesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateAddressesGet(params?: ApiBogusGenerateAddressesGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateAddressesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiBogusGenerateClientsGet()` */
  static readonly ApiBogusGenerateClientsGetPath = '/api/bogus/generateClients';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateClientsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateClientsGet$Response(params?: ApiBogusGenerateClientsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateClientsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateClientsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateClientsGet(params?: ApiBogusGenerateClientsGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateClientsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiBogusGenerateOrdersGet()` */
  static readonly ApiBogusGenerateOrdersGetPath = '/api/bogus/generateOrders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateOrdersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateOrdersGet$Response(params?: ApiBogusGenerateOrdersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateOrdersGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateOrdersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateOrdersGet(params?: ApiBogusGenerateOrdersGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateOrdersGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiBogusGenerateMissionsGet()` */
  static readonly ApiBogusGenerateMissionsGetPath = '/api/bogus/generateMissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateMissionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateMissionsGet$Response(params?: ApiBogusGenerateMissionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateMissionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateMissionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateMissionsGet(params?: ApiBogusGenerateMissionsGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateMissionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiBogusGenerateUserAbsenceGet()` */
  static readonly ApiBogusGenerateUserAbsenceGetPath = '/api/bogus/generate-user-absence';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateUserAbsenceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateUserAbsenceGet$Response(params?: ApiBogusGenerateUserAbsenceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateUserAbsenceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateUserAbsenceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateUserAbsenceGet(params?: ApiBogusGenerateUserAbsenceGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateUserAbsenceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiBogusGenerateDefaultSettingGet()` */
  static readonly ApiBogusGenerateDefaultSettingGetPath = '/api/bogus/generate-default-setting';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBogusGenerateDefaultSettingGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateDefaultSettingGet$Response(params?: ApiBogusGenerateDefaultSettingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiBogusGenerateDefaultSettingGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBogusGenerateDefaultSettingGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBogusGenerateDefaultSettingGet(params?: ApiBogusGenerateDefaultSettingGet$Params, context?: HttpContext): Observable<void> {
    return this.apiBogusGenerateDefaultSettingGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
