/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ClientAutoCompleteOutput } from '../models/client-auto-complete-output';
import { ClientListOutputListResponse } from '../models/client-list-output-list-response';
import { ClientOutput } from '../models/client-output';
import { clientsAutocompleteGet } from '../fn/clients/clients-autocomplete-get';
import { ClientsAutocompleteGet$Params } from '../fn/clients/clients-autocomplete-get';
import { clientsDatagridPost } from '../fn/clients/clients-datagrid-post';
import { ClientsDatagridPost$Params } from '../fn/clients/clients-datagrid-post';
import { clientsIdDelete } from '../fn/clients/clients-id-delete';
import { ClientsIdDelete$Params } from '../fn/clients/clients-id-delete';
import { clientsIdGet } from '../fn/clients/clients-id-get';
import { ClientsIdGet$Params } from '../fn/clients/clients-id-get';
import { clientsIdPut } from '../fn/clients/clients-id-put';
import { ClientsIdPut$Params } from '../fn/clients/clients-id-put';
import { clientsPost } from '../fn/clients/clients-post';
import { ClientsPost$Params } from '../fn/clients/clients-post';

@Injectable({ providedIn: 'root' })
export class ClientsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `clientsDatagridPost()` */
  static readonly ClientsDatagridPostPath = '/clients/datagrid';

  /**
   * Récupérer la liste des clients avec filtres dynamiques OData.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientsDatagridPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsDatagridPost$Response(params?: ClientsDatagridPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientListOutputListResponse>> {
    return clientsDatagridPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des clients avec filtres dynamiques OData.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientsDatagridPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsDatagridPost(params?: ClientsDatagridPost$Params, context?: HttpContext): Observable<ClientListOutputListResponse> {
    return this.clientsDatagridPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientListOutputListResponse>): ClientListOutputListResponse => r.body)
    );
  }

  /** Path part for operation `clientsIdGet()` */
  static readonly ClientsIdGetPath = '/clients/{id}';

  /**
   * Récupérer les détails d'un client.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsIdGet$Response(params: ClientsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientOutput>> {
    return clientsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'un client.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsIdGet(params: ClientsIdGet$Params, context?: HttpContext): Observable<ClientOutput> {
    return this.clientsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientOutput>): ClientOutput => r.body)
    );
  }

  /** Path part for operation `clientsIdPut()` */
  static readonly ClientsIdPutPath = '/clients/{id}';

  /**
   * Modification d'un client.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientsIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientsIdPut$Response(params: ClientsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientOutput>> {
    return clientsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modification d'un client.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientsIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientsIdPut(params: ClientsIdPut$Params, context?: HttpContext): Observable<ClientOutput> {
    return this.clientsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientOutput>): ClientOutput => r.body)
    );
  }

  /** Path part for operation `clientsIdDelete()` */
  static readonly ClientsIdDeletePath = '/clients/{id}';

  /**
   * Suppression d'un client.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsIdDelete$Response(params: ClientsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return clientsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Suppression d'un client.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsIdDelete(params: ClientsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.clientsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `clientsPost()` */
  static readonly ClientsPostPath = '/clients';

  /**
   * Inscription d'un client.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientsPost$Response(params?: ClientsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return clientsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Inscription d'un client.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientsPost(params?: ClientsPost$Params, context?: HttpContext): Observable<string> {
    return this.clientsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `clientsAutocompleteGet()` */
  static readonly ClientsAutocompleteGetPath = '/clients/autocomplete';

  /**
   * Récupérer les clients par rapport à l'autocomplétion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientsAutocompleteGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsAutocompleteGet$Response(params?: ClientsAutocompleteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientAutoCompleteOutput>>> {
    return clientsAutocompleteGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les clients par rapport à l'autocomplétion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientsAutocompleteGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientsAutocompleteGet(params?: ClientsAutocompleteGet$Params, context?: HttpContext): Observable<Array<ClientAutoCompleteOutput>> {
    return this.clientsAutocompleteGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ClientAutoCompleteOutput>>): Array<ClientAutoCompleteOutput> => r.body)
    );
  }

}
