/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CustomFormListOutput } from '../models/custom-form-list-output';
import { CustomFormListOutputListResponse } from '../models/custom-form-list-output-list-response';
import { CustomFormOutput } from '../models/custom-form-output';
import { customFormsByMissionTypeMissionTypeIdBaseAnswerGet } from '../fn/custom-forms/custom-forms-by-mission-type-mission-type-id-base-answer-get';
import { CustomFormsByMissionTypeMissionTypeIdBaseAnswerGet$Params } from '../fn/custom-forms/custom-forms-by-mission-type-mission-type-id-base-answer-get';
import { customFormsByMissionTypeMissionTypeIdGet } from '../fn/custom-forms/custom-forms-by-mission-type-mission-type-id-get';
import { CustomFormsByMissionTypeMissionTypeIdGet$Params } from '../fn/custom-forms/custom-forms-by-mission-type-mission-type-id-get';
import { customFormsDefaultGet } from '../fn/custom-forms/custom-forms-default-get';
import { CustomFormsDefaultGet$Params } from '../fn/custom-forms/custom-forms-default-get';
import { customFormsFieldTypesGet } from '../fn/custom-forms/custom-forms-field-types-get';
import { CustomFormsFieldTypesGet$Params } from '../fn/custom-forms/custom-forms-field-types-get';
import { customFormsGet } from '../fn/custom-forms/custom-forms-get';
import { CustomFormsGet$Params } from '../fn/custom-forms/custom-forms-get';
import { customFormsIdDelete } from '../fn/custom-forms/custom-forms-id-delete';
import { CustomFormsIdDelete$Params } from '../fn/custom-forms/custom-forms-id-delete';
import { customFormsIdGet } from '../fn/custom-forms/custom-forms-id-get';
import { CustomFormsIdGet$Params } from '../fn/custom-forms/custom-forms-id-get';
import { customFormsIdPut } from '../fn/custom-forms/custom-forms-id-put';
import { CustomFormsIdPut$Params } from '../fn/custom-forms/custom-forms-id-put';
import { customFormsIdUnarchivePost } from '../fn/custom-forms/custom-forms-id-unarchive-post';
import { CustomFormsIdUnarchivePost$Params } from '../fn/custom-forms/custom-forms-id-unarchive-post';
import { customFormsPost } from '../fn/custom-forms/custom-forms-post';
import { CustomFormsPost$Params } from '../fn/custom-forms/custom-forms-post';
import { CustomFormWithBaseAnswerOutput } from '../models/custom-form-with-base-answer-output';
import { FieldTypeDefinition } from '../models/field-type-definition';
import { FormStructure } from '../models/form-structure';

@Injectable({ providedIn: 'root' })
export class CustomFormsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `customFormsGet()` */
  static readonly CustomFormsGetPath = '/custom-forms';

  /**
   * Récupérer la liste des types de formulaire.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsGet$Response(params?: CustomFormsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormListOutputListResponse>> {
    return customFormsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des types de formulaire.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsGet(params?: CustomFormsGet$Params, context?: HttpContext): Observable<CustomFormListOutputListResponse> {
    return this.customFormsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomFormListOutputListResponse>): CustomFormListOutputListResponse => r.body)
    );
  }

  /** Path part for operation `customFormsPost()` */
  static readonly CustomFormsPostPath = '/custom-forms';

  /**
   * Créer un nouveau type de formulaire.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  customFormsPost$Response(params?: CustomFormsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormOutput>> {
    return customFormsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau type de formulaire.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  customFormsPost(params?: CustomFormsPost$Params, context?: HttpContext): Observable<CustomFormOutput> {
    return this.customFormsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomFormOutput>): CustomFormOutput => r.body)
    );
  }

  /** Path part for operation `customFormsIdGet()` */
  static readonly CustomFormsIdGetPath = '/custom-forms/{id}';

  /**
   * Récupérer un custom form par son ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsIdGet$Response(params: CustomFormsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormOutput>> {
    return customFormsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un custom form par son ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsIdGet(params: CustomFormsIdGet$Params, context?: HttpContext): Observable<CustomFormOutput> {
    return this.customFormsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomFormOutput>): CustomFormOutput => r.body)
    );
  }

  /** Path part for operation `customFormsIdPut()` */
  static readonly CustomFormsIdPutPath = '/custom-forms/{id}';

  /**
   * Met à jour un type de formulaire.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  customFormsIdPut$Response(params: CustomFormsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormOutput>> {
    return customFormsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Met à jour un type de formulaire.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  customFormsIdPut(params: CustomFormsIdPut$Params, context?: HttpContext): Observable<CustomFormOutput> {
    return this.customFormsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomFormOutput>): CustomFormOutput => r.body)
    );
  }

  /** Path part for operation `customFormsIdDelete()` */
  static readonly CustomFormsIdDeletePath = '/custom-forms/{id}';

  /**
   * Supprime un custom form.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsIdDelete$Response(params: CustomFormsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return customFormsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprime un custom form.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsIdDelete(params: CustomFormsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.customFormsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `customFormsIdUnarchivePost()` */
  static readonly CustomFormsIdUnarchivePostPath = '/custom-forms/{id}/unarchive';

  /**
   * Désarchiver un custom form.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsIdUnarchivePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsIdUnarchivePost$Response(params: CustomFormsIdUnarchivePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return customFormsIdUnarchivePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Désarchiver un custom form.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsIdUnarchivePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsIdUnarchivePost(params: CustomFormsIdUnarchivePost$Params, context?: HttpContext): Observable<void> {
    return this.customFormsIdUnarchivePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `customFormsDefaultGet()` */
  static readonly CustomFormsDefaultGetPath = '/custom-forms/default';

  /**
   * Récupère le custom form par défaut.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsDefaultGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsDefaultGet$Response(params?: CustomFormsDefaultGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FormStructure>> {
    return customFormsDefaultGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère le custom form par défaut.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsDefaultGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsDefaultGet(params?: CustomFormsDefaultGet$Params, context?: HttpContext): Observable<FormStructure> {
    return this.customFormsDefaultGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<FormStructure>): FormStructure => r.body)
    );
  }

  /** Path part for operation `customFormsFieldTypesGet()` */
  static readonly CustomFormsFieldTypesGetPath = '/custom-forms/field-types';

  /**
   * Récupère les types de champs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsFieldTypesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsFieldTypesGet$Response(params?: CustomFormsFieldTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: FieldTypeDefinition;
}>> {
    return customFormsFieldTypesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère les types de champs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsFieldTypesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsFieldTypesGet(params?: CustomFormsFieldTypesGet$Params, context?: HttpContext): Observable<{
[key: string]: FieldTypeDefinition;
}> {
    return this.customFormsFieldTypesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: FieldTypeDefinition;
}>): {
[key: string]: FieldTypeDefinition;
} => r.body)
    );
  }

  /** Path part for operation `customFormsByMissionTypeMissionTypeIdGet()` */
  static readonly CustomFormsByMissionTypeMissionTypeIdGetPath = '/custom-forms/by-mission-type/{missionTypeId}';

  /**
   * Récupère le custom form associé à un type de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsByMissionTypeMissionTypeIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsByMissionTypeMissionTypeIdGet$Response(params: CustomFormsByMissionTypeMissionTypeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomFormListOutput>>> {
    return customFormsByMissionTypeMissionTypeIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère le custom form associé à un type de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsByMissionTypeMissionTypeIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsByMissionTypeMissionTypeIdGet(params: CustomFormsByMissionTypeMissionTypeIdGet$Params, context?: HttpContext): Observable<Array<CustomFormListOutput>> {
    return this.customFormsByMissionTypeMissionTypeIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CustomFormListOutput>>): Array<CustomFormListOutput> => r.body)
    );
  }

  /** Path part for operation `customFormsByMissionTypeMissionTypeIdBaseAnswerGet()` */
  static readonly CustomFormsByMissionTypeMissionTypeIdBaseAnswerGetPath = '/custom-forms/by-mission-type/{missionTypeId}/base-answer';

  /**
   * Récupère le custom form associé à un type de mission avec les données de base.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customFormsByMissionTypeMissionTypeIdBaseAnswerGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsByMissionTypeMissionTypeIdBaseAnswerGet$Response(params: CustomFormsByMissionTypeMissionTypeIdBaseAnswerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomFormWithBaseAnswerOutput>>> {
    return customFormsByMissionTypeMissionTypeIdBaseAnswerGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère le custom form associé à un type de mission avec les données de base.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customFormsByMissionTypeMissionTypeIdBaseAnswerGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customFormsByMissionTypeMissionTypeIdBaseAnswerGet(params: CustomFormsByMissionTypeMissionTypeIdBaseAnswerGet$Params, context?: HttpContext): Observable<Array<CustomFormWithBaseAnswerOutput>> {
    return this.customFormsByMissionTypeMissionTypeIdBaseAnswerGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CustomFormWithBaseAnswerOutput>>): Array<CustomFormWithBaseAnswerOutput> => r.body)
    );
  }

}
