/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { filesFileNameDelete } from '../fn/files/files-file-name-delete';
import { FilesFileNameDelete$Params } from '../fn/files/files-file-name-delete';
import { filesFileNameGet } from '../fn/files/files-file-name-get';
import { FilesFileNameGet$Params } from '../fn/files/files-file-name-get';
import { filesPost$FormData } from '../fn/files/files-post-form-data';
import { FilesPost$FormData$Params } from '../fn/files/files-post-form-data';
import { filesPost$Json } from '../fn/files/files-post-json';
import { FilesPost$Json$Params } from '../fn/files/files-post-json';
import { filesSettingsFlaviconPost$FormData } from '../fn/files/files-settings-flavicon-post-form-data';
import { FilesSettingsFlaviconPost$FormData$Params } from '../fn/files/files-settings-flavicon-post-form-data';
import { filesSettingsFlaviconPost$Json } from '../fn/files/files-settings-flavicon-post-json';
import { FilesSettingsFlaviconPost$Json$Params } from '../fn/files/files-settings-flavicon-post-json';
import { filesSettingsLogoPost$FormData } from '../fn/files/files-settings-logo-post-form-data';
import { FilesSettingsLogoPost$FormData$Params } from '../fn/files/files-settings-logo-post-form-data';
import { filesSettingsLogoPost$Json } from '../fn/files/files-settings-logo-post-json';
import { FilesSettingsLogoPost$Json$Params } from '../fn/files/files-settings-logo-post-json';
import { filesUrlFileNameGet } from '../fn/files/files-url-file-name-get';
import { FilesUrlFileNameGet$Params } from '../fn/files/files-url-file-name-get';
import { FileUrlResponse } from '../models/file-url-response';

@Injectable({ providedIn: 'root' })
export class FilesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `filesPost()` */
  static readonly FilesPostPath = '/files';

  /**
   * Upload a file to the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesPost$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesPost$FormData$Response(params?: FilesPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesPost$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload a file to the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesPost$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesPost$FormData(params?: FilesPost$FormData$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesPost$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

  /**
   * Upload a file to the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesPost$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  filesPost$Json$Response(params?: FilesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload a file to the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesPost$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  filesPost$Json(params?: FilesPost$Json$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

  /** Path part for operation `filesFileNameGet()` */
  static readonly FilesFileNameGetPath = '/files/fileName';

  /**
   * Download a file from the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesFileNameGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesFileNameGet$Response(params?: FilesFileNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return filesFileNameGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Download a file from the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesFileNameGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesFileNameGet(params?: FilesFileNameGet$Params, context?: HttpContext): Observable<void> {
    return this.filesFileNameGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `filesFileNameDelete()` */
  static readonly FilesFileNameDeletePath = '/files/fileName';

  /**
   * Delete a file from the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesFileNameDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesFileNameDelete$Response(params?: FilesFileNameDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return filesFileNameDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a file from the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesFileNameDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesFileNameDelete(params?: FilesFileNameDelete$Params, context?: HttpContext): Observable<void> {
    return this.filesFileNameDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `filesUrlFileNameGet()` */
  static readonly FilesUrlFileNameGetPath = '/files/url/{fileName}';

  /**
   * Get the URL of a file from the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesUrlFileNameGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesUrlFileNameGet$Response(params: FilesUrlFileNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesUrlFileNameGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the URL of a file from the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesUrlFileNameGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesUrlFileNameGet(params: FilesUrlFileNameGet$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesUrlFileNameGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

  /** Path part for operation `filesSettingsLogoPost()` */
  static readonly FilesSettingsLogoPostPath = '/files/settings/logo';

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesSettingsLogoPost$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesSettingsLogoPost$FormData$Response(params?: FilesSettingsLogoPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesSettingsLogoPost$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesSettingsLogoPost$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesSettingsLogoPost$FormData(params?: FilesSettingsLogoPost$FormData$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesSettingsLogoPost$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesSettingsLogoPost$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  filesSettingsLogoPost$Json$Response(params?: FilesSettingsLogoPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesSettingsLogoPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesSettingsLogoPost$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  filesSettingsLogoPost$Json(params?: FilesSettingsLogoPost$Json$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesSettingsLogoPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

  /** Path part for operation `filesSettingsFlaviconPost()` */
  static readonly FilesSettingsFlaviconPostPath = '/files/settings/flavicon';

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesSettingsFlaviconPost$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesSettingsFlaviconPost$FormData$Response(params?: FilesSettingsFlaviconPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesSettingsFlaviconPost$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesSettingsFlaviconPost$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesSettingsFlaviconPost$FormData(params?: FilesSettingsFlaviconPost$FormData$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesSettingsFlaviconPost$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesSettingsFlaviconPost$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  filesSettingsFlaviconPost$Json$Response(params?: FilesSettingsFlaviconPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
    return filesSettingsFlaviconPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload a logo to the Minio server.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesSettingsFlaviconPost$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  filesSettingsFlaviconPost$Json(params?: FilesSettingsFlaviconPost$Json$Params, context?: HttpContext): Observable<FileUrlResponse> {
    return this.filesSettingsFlaviconPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileUrlResponse>): FileUrlResponse => r.body)
    );
  }

}
