/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { missionStatusesGet } from '../fn/mission-statuses/mission-statuses-get';
import { MissionStatusesGet$Params } from '../fn/mission-statuses/mission-statuses-get';
import { missionStatusesIdDelete } from '../fn/mission-statuses/mission-statuses-id-delete';
import { MissionStatusesIdDelete$Params } from '../fn/mission-statuses/mission-statuses-id-delete';
import { missionStatusesIdGet } from '../fn/mission-statuses/mission-statuses-id-get';
import { MissionStatusesIdGet$Params } from '../fn/mission-statuses/mission-statuses-id-get';
import { missionStatusesIdPut } from '../fn/mission-statuses/mission-statuses-id-put';
import { MissionStatusesIdPut$Params } from '../fn/mission-statuses/mission-statuses-id-put';
import { missionStatusesPost } from '../fn/mission-statuses/mission-statuses-post';
import { MissionStatusesPost$Params } from '../fn/mission-statuses/mission-statuses-post';
import { MissionStatusOutput } from '../models/mission-status-output';

@Injectable({ providedIn: 'root' })
export class MissionStatusesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `missionStatusesGet()` */
  static readonly MissionStatusesGetPath = '/mission-statuses';

  /**
   * Récupérer la liste des statuts de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionStatusesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionStatusesGet$Response(params?: MissionStatusesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionStatusOutput>>> {
    return missionStatusesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des statuts de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionStatusesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionStatusesGet(params?: MissionStatusesGet$Params, context?: HttpContext): Observable<Array<MissionStatusOutput>> {
    return this.missionStatusesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MissionStatusOutput>>): Array<MissionStatusOutput> => r.body)
    );
  }

  /** Path part for operation `missionStatusesPost()` */
  static readonly MissionStatusesPostPath = '/mission-statuses';

  /**
   * Créer un nouveau statut de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionStatusesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionStatusesPost$Response(params?: MissionStatusesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionStatusOutput>> {
    return missionStatusesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau statut de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionStatusesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionStatusesPost(params?: MissionStatusesPost$Params, context?: HttpContext): Observable<MissionStatusOutput> {
    return this.missionStatusesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionStatusOutput>): MissionStatusOutput => r.body)
    );
  }

  /** Path part for operation `missionStatusesIdGet()` */
  static readonly MissionStatusesIdGetPath = '/mission-statuses/{id}';

  /**
   * Récupérer les détails d’un statut de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionStatusesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionStatusesIdGet$Response(params: MissionStatusesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionStatusOutput>> {
    return missionStatusesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d’un statut de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionStatusesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionStatusesIdGet(params: MissionStatusesIdGet$Params, context?: HttpContext): Observable<MissionStatusOutput> {
    return this.missionStatusesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionStatusOutput>): MissionStatusOutput => r.body)
    );
  }

  /** Path part for operation `missionStatusesIdPut()` */
  static readonly MissionStatusesIdPutPath = '/mission-statuses/{id}';

  /**
   * Modifier un statut de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionStatusesIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionStatusesIdPut$Response(params: MissionStatusesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionStatusOutput>> {
    return missionStatusesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modifier un statut de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionStatusesIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionStatusesIdPut(params: MissionStatusesIdPut$Params, context?: HttpContext): Observable<MissionStatusOutput> {
    return this.missionStatusesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionStatusOutput>): MissionStatusOutput => r.body)
    );
  }

  /** Path part for operation `missionStatusesIdDelete()` */
  static readonly MissionStatusesIdDeletePath = '/mission-statuses/{id}';

  /**
   * Supprimer un statut de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionStatusesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionStatusesIdDelete$Response(params: MissionStatusesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return missionStatusesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un statut de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionStatusesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionStatusesIdDelete(params: MissionStatusesIdDelete$Params, context?: HttpContext): Observable<string> {
    return this.missionStatusesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
