/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AddressOutputListResponse } from '../models/address-output-list-response';
import { FileInfoResponse } from '../models/file-info-response';
import { MissionListOutputListResponse } from '../models/mission-list-output-list-response';
import { MissionOutput } from '../models/mission-output';
import { missionsAddressesPost } from '../fn/missions/missions-addresses-post';
import { MissionsAddressesPost$Params } from '../fn/missions/missions-addresses-post';
import { missionsAssignPut } from '../fn/missions/missions-assign-put';
import { MissionsAssignPut$Params } from '../fn/missions/missions-assign-put';
import { missionsDatagridGet } from '../fn/missions/missions-datagrid-get';
import { MissionsDatagridGet$Params } from '../fn/missions/missions-datagrid-get';
import { missionsIdDelete } from '../fn/missions/missions-id-delete';
import { MissionsIdDelete$Params } from '../fn/missions/missions-id-delete';
import { missionsIdGet } from '../fn/missions/missions-id-get';
import { MissionsIdGet$Params } from '../fn/missions/missions-id-get';
import { missionsIdPut } from '../fn/missions/missions-id-put';
import { MissionsIdPut$Params } from '../fn/missions/missions-id-put';
import { missionsIdUnarchivePost } from '../fn/missions/missions-id-unarchive-post';
import { MissionsIdUnarchivePost$Params } from '../fn/missions/missions-id-unarchive-post';
import { missionsMissionIdDuplicateGet } from '../fn/missions/missions-mission-id-duplicate-get';
import { MissionsMissionIdDuplicateGet$Params } from '../fn/missions/missions-mission-id-duplicate-get';
import { missionsMissionIdFilesFileNameDelete } from '../fn/missions/missions-mission-id-files-file-name-delete';
import { MissionsMissionIdFilesFileNameDelete$Params } from '../fn/missions/missions-mission-id-files-file-name-delete';
import { missionsMissionIdFilesGet } from '../fn/missions/missions-mission-id-files-get';
import { MissionsMissionIdFilesGet$Params } from '../fn/missions/missions-mission-id-files-get';
import { missionsMissionIdFilesPost$FormData } from '../fn/missions/missions-mission-id-files-post-form-data';
import { MissionsMissionIdFilesPost$FormData$Params } from '../fn/missions/missions-mission-id-files-post-form-data';
import { missionsMissionIdFilesPost$Json } from '../fn/missions/missions-mission-id-files-post-json';
import { MissionsMissionIdFilesPost$Json$Params } from '../fn/missions/missions-mission-id-files-post-json';
import { missionsMissionIdPicturesFileNameDelete } from '../fn/missions/missions-mission-id-pictures-file-name-delete';
import { MissionsMissionIdPicturesFileNameDelete$Params } from '../fn/missions/missions-mission-id-pictures-file-name-delete';
import { missionsMissionIdPicturesGet } from '../fn/missions/missions-mission-id-pictures-get';
import { MissionsMissionIdPicturesGet$Params } from '../fn/missions/missions-mission-id-pictures-get';
import { missionsMissionIdPicturesPost$FormData } from '../fn/missions/missions-mission-id-pictures-post-form-data';
import { MissionsMissionIdPicturesPost$FormData$Params } from '../fn/missions/missions-mission-id-pictures-post-form-data';
import { missionsMissionIdPicturesPost$Json } from '../fn/missions/missions-mission-id-pictures-post-json';
import { MissionsMissionIdPicturesPost$Json$Params } from '../fn/missions/missions-mission-id-pictures-post-json';
import { missionsMissionsDetailedGet } from '../fn/missions/missions-missions-detailed-get';
import { MissionsMissionsDetailedGet$Params } from '../fn/missions/missions-missions-detailed-get';
import { missionsPost } from '../fn/missions/missions-post';
import { MissionsPost$Params } from '../fn/missions/missions-post';
import { missionsReArrangPut } from '../fn/missions/missions-re-arrang-put';
import { MissionsReArrangPut$Params } from '../fn/missions/missions-re-arrang-put';
import { missionsUnaffectedGet } from '../fn/missions/missions-unaffected-get';
import { MissionsUnaffectedGet$Params } from '../fn/missions/missions-unaffected-get';
import { missionsUnassignPut } from '../fn/missions/missions-unassign-put';
import { MissionsUnassignPut$Params } from '../fn/missions/missions-unassign-put';
import { missionsUpdateMissionAffectationVisibilityPut } from '../fn/missions/missions-update-mission-affectation-visibility-put';
import { MissionsUpdateMissionAffectationVisibilityPut$Params } from '../fn/missions/missions-update-mission-affectation-visibility-put';
import { missionsUpdateMissionVisibilityPut } from '../fn/missions/missions-update-mission-visibility-put';
import { MissionsUpdateMissionVisibilityPut$Params } from '../fn/missions/missions-update-mission-visibility-put';

@Injectable({ providedIn: 'root' })
export class MissionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `missionsDatagridGet()` */
  static readonly MissionsDatagridGetPath = '/missions/datagrid';

  /**
   * Récupérer la liste filtrée des missions via OData dans un POST (évite la limite de longueur d'URL).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsDatagridGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsDatagridGet$Response(params?: MissionsDatagridGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionListOutputListResponse>> {
    return missionsDatagridGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste filtrée des missions via OData dans un POST (évite la limite de longueur d'URL).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsDatagridGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsDatagridGet(params?: MissionsDatagridGet$Params, context?: HttpContext): Observable<MissionListOutputListResponse> {
    return this.missionsDatagridGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionListOutputListResponse>): MissionListOutputListResponse => r.body)
    );
  }

  /** Path part for operation `missionsUnaffectedGet()` */
  static readonly MissionsUnaffectedGetPath = '/missions/unaffected';

  /**
   * Récupérer la liste filtrée des missions via OData dans un POST (évite la limite de longueur d'URL).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsUnaffectedGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsUnaffectedGet$Response(params?: MissionsUnaffectedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionOutput>>> {
    return missionsUnaffectedGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste filtrée des missions via OData dans un POST (évite la limite de longueur d'URL).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsUnaffectedGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsUnaffectedGet(params?: MissionsUnaffectedGet$Params, context?: HttpContext): Observable<Array<MissionOutput>> {
    return this.missionsUnaffectedGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MissionOutput>>): Array<MissionOutput> => r.body)
    );
  }

  /** Path part for operation `missionsAddressesPost()` */
  static readonly MissionsAddressesPostPath = '/missions/addresses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsAddressesPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsAddressesPost$Response(params?: MissionsAddressesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AddressOutputListResponse>> {
    return missionsAddressesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsAddressesPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsAddressesPost(params?: MissionsAddressesPost$Params, context?: HttpContext): Observable<AddressOutputListResponse> {
    return this.missionsAddressesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<AddressOutputListResponse>): AddressOutputListResponse => r.body)
    );
  }

  /** Path part for operation `missionsIdGet()` */
  static readonly MissionsIdGetPath = '/missions/{id}';

  /**
   * Récupérer les détails d'une mission par son identifiant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsIdGet$Response(params: MissionsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
    return missionsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'une mission par son identifiant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsIdGet(params: MissionsIdGet$Params, context?: HttpContext): Observable<MissionOutput> {
    return this.missionsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionOutput>): MissionOutput => r.body)
    );
  }

  /** Path part for operation `missionsIdPut()` */
  static readonly MissionsIdPutPath = '/missions/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsIdPut$Response(params: MissionsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
    return missionsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsIdPut(params: MissionsIdPut$Params, context?: HttpContext): Observable<MissionOutput> {
    return this.missionsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionOutput>): MissionOutput => r.body)
    );
  }

  /** Path part for operation `missionsIdDelete()` */
  static readonly MissionsIdDeletePath = '/missions/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsIdDelete$Response(params: MissionsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return missionsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsIdDelete(params: MissionsIdDelete$Params, context?: HttpContext): Observable<string> {
    return this.missionsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `missionsPost()` */
  static readonly MissionsPostPath = '/missions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsPost$Response(params?: MissionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return missionsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsPost(params?: MissionsPost$Params, context?: HttpContext): Observable<string> {
    return this.missionsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `missionsMissionsDetailedGet()` */
  static readonly MissionsMissionsDetailedGetPath = '/missions/missions-detailed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionsDetailedGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionsDetailedGet$Response(params?: MissionsMissionsDetailedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionOutput>>> {
    return missionsMissionsDetailedGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionsDetailedGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionsDetailedGet(params?: MissionsMissionsDetailedGet$Params, context?: HttpContext): Observable<Array<MissionOutput>> {
    return this.missionsMissionsDetailedGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MissionOutput>>): Array<MissionOutput> => r.body)
    );
  }

  /** Path part for operation `missionsAssignPut()` */
  static readonly MissionsAssignPutPath = '/missions/assign';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsAssignPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsAssignPut$Response(params?: MissionsAssignPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
    return missionsAssignPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsAssignPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsAssignPut(params?: MissionsAssignPut$Params, context?: HttpContext): Observable<MissionOutput> {
    return this.missionsAssignPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionOutput>): MissionOutput => r.body)
    );
  }

  /** Path part for operation `missionsReArrangPut()` */
  static readonly MissionsReArrangPutPath = '/missions/re-arrang';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsReArrangPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsReArrangPut$Response(params?: MissionsReArrangPut$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return missionsReArrangPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsReArrangPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsReArrangPut(params?: MissionsReArrangPut$Params, context?: HttpContext): Observable<string> {
    return this.missionsReArrangPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `missionsUnassignPut()` */
  static readonly MissionsUnassignPutPath = '/missions/unassign';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsUnassignPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsUnassignPut$Response(params?: MissionsUnassignPut$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return missionsUnassignPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsUnassignPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsUnassignPut(params?: MissionsUnassignPut$Params, context?: HttpContext): Observable<string> {
    return this.missionsUnassignPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `missionsUpdateMissionVisibilityPut()` */
  static readonly MissionsUpdateMissionVisibilityPutPath = '/missions/update-mission-visibility';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsUpdateMissionVisibilityPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsUpdateMissionVisibilityPut$Response(params?: MissionsUpdateMissionVisibilityPut$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return missionsUpdateMissionVisibilityPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsUpdateMissionVisibilityPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsUpdateMissionVisibilityPut(params?: MissionsUpdateMissionVisibilityPut$Params, context?: HttpContext): Observable<boolean> {
    return this.missionsUpdateMissionVisibilityPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `missionsUpdateMissionAffectationVisibilityPut()` */
  static readonly MissionsUpdateMissionAffectationVisibilityPutPath = '/missions/update-mission-affectation-visibility';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsUpdateMissionAffectationVisibilityPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsUpdateMissionAffectationVisibilityPut$Response(params?: MissionsUpdateMissionAffectationVisibilityPut$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return missionsUpdateMissionAffectationVisibilityPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsUpdateMissionAffectationVisibilityPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsUpdateMissionAffectationVisibilityPut(params?: MissionsUpdateMissionAffectationVisibilityPut$Params, context?: HttpContext): Observable<boolean> {
    return this.missionsUpdateMissionAffectationVisibilityPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `missionsIdUnarchivePost()` */
  static readonly MissionsIdUnarchivePostPath = '/missions/{id}/unarchive';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsIdUnarchivePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsIdUnarchivePost$Response(params: MissionsIdUnarchivePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return missionsIdUnarchivePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsIdUnarchivePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsIdUnarchivePost(params: MissionsIdUnarchivePost$Params, context?: HttpContext): Observable<void> {
    return this.missionsIdUnarchivePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdDuplicateGet()` */
  static readonly MissionsMissionIdDuplicateGetPath = '/missions/{missionId}/duplicate';

  /**
   * Duplique une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdDuplicateGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdDuplicateGet$Response(params: MissionsMissionIdDuplicateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
    return missionsMissionIdDuplicateGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Duplique une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdDuplicateGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdDuplicateGet(params: MissionsMissionIdDuplicateGet$Params, context?: HttpContext): Observable<MissionOutput> {
    return this.missionsMissionIdDuplicateGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionOutput>): MissionOutput => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdPicturesGet()` */
  static readonly MissionsMissionIdPicturesGetPath = '/missions/{missionId}/pictures';

  /**
   * Récupère toutes les photos/images d'une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdPicturesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdPicturesGet$Response(params: MissionsMissionIdPicturesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileInfoResponse>>> {
    return missionsMissionIdPicturesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère toutes les photos/images d'une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdPicturesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdPicturesGet(params: MissionsMissionIdPicturesGet$Params, context?: HttpContext): Observable<Array<FileInfoResponse>> {
    return this.missionsMissionIdPicturesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileInfoResponse>>): Array<FileInfoResponse> => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdPicturesPost()` */
  static readonly MissionsMissionIdPicturesPostPath = '/missions/{missionId}/pictures';

  /**
   * Upload une image/photo pour une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdPicturesPost$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  missionsMissionIdPicturesPost$FormData$Response(params: MissionsMissionIdPicturesPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
    return missionsMissionIdPicturesPost$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload une image/photo pour une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdPicturesPost$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  missionsMissionIdPicturesPost$FormData(params: MissionsMissionIdPicturesPost$FormData$Params, context?: HttpContext): Observable<FileInfoResponse> {
    return this.missionsMissionIdPicturesPost$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponse>): FileInfoResponse => r.body)
    );
  }

  /**
   * Upload une image/photo pour une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdPicturesPost$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsMissionIdPicturesPost$Json$Response(params: MissionsMissionIdPicturesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
    return missionsMissionIdPicturesPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload une image/photo pour une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdPicturesPost$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsMissionIdPicturesPost$Json(params: MissionsMissionIdPicturesPost$Json$Params, context?: HttpContext): Observable<FileInfoResponse> {
    return this.missionsMissionIdPicturesPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponse>): FileInfoResponse => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdFilesGet()` */
  static readonly MissionsMissionIdFilesGetPath = '/missions/{missionId}/files';

  /**
   * Récupère tous les fichiers (documents) d'une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdFilesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdFilesGet$Response(params: MissionsMissionIdFilesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileInfoResponse>>> {
    return missionsMissionIdFilesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère tous les fichiers (documents) d'une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdFilesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdFilesGet(params: MissionsMissionIdFilesGet$Params, context?: HttpContext): Observable<Array<FileInfoResponse>> {
    return this.missionsMissionIdFilesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileInfoResponse>>): Array<FileInfoResponse> => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdFilesPost()` */
  static readonly MissionsMissionIdFilesPostPath = '/missions/{missionId}/files';

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdFilesPost$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  missionsMissionIdFilesPost$FormData$Response(params: MissionsMissionIdFilesPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
    return missionsMissionIdFilesPost$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdFilesPost$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  missionsMissionIdFilesPost$FormData(params: MissionsMissionIdFilesPost$FormData$Params, context?: HttpContext): Observable<FileInfoResponse> {
    return this.missionsMissionIdFilesPost$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponse>): FileInfoResponse => r.body)
    );
  }

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdFilesPost$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsMissionIdFilesPost$Json$Response(params: MissionsMissionIdFilesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
    return missionsMissionIdFilesPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdFilesPost$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionsMissionIdFilesPost$Json(params: MissionsMissionIdFilesPost$Json$Params, context?: HttpContext): Observable<FileInfoResponse> {
    return this.missionsMissionIdFilesPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponse>): FileInfoResponse => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdFilesFileNameDelete()` */
  static readonly MissionsMissionIdFilesFileNameDeletePath = '/missions/{missionId}/files/{fileName}';

  /**
   * Supprime un fichier d'une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdFilesFileNameDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdFilesFileNameDelete$Response(params: MissionsMissionIdFilesFileNameDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return missionsMissionIdFilesFileNameDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprime un fichier d'une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdFilesFileNameDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdFilesFileNameDelete(params: MissionsMissionIdFilesFileNameDelete$Params, context?: HttpContext): Observable<void> {
    return this.missionsMissionIdFilesFileNameDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `missionsMissionIdPicturesFileNameDelete()` */
  static readonly MissionsMissionIdPicturesFileNameDeletePath = '/missions/{missionId}/pictures/{fileName}';

  /**
   * Supprime une photo d'une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionsMissionIdPicturesFileNameDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdPicturesFileNameDelete$Response(params: MissionsMissionIdPicturesFileNameDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return missionsMissionIdPicturesFileNameDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprime une photo d'une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionsMissionIdPicturesFileNameDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionsMissionIdPicturesFileNameDelete(params: MissionsMissionIdPicturesFileNameDelete$Params, context?: HttpContext): Observable<void> {
    return this.missionsMissionIdPicturesFileNameDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
