/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { MissionTypeListOutput } from '../models/mission-type-list-output';
import { MissionTypeListOutputListResponse } from '../models/mission-type-list-output-list-response';
import { MissionTypeOutput } from '../models/mission-type-output';
import { missionTypesByOrderTypeOrderTypeIdGet } from '../fn/mission-types/mission-types-by-order-type-order-type-id-get';
import { MissionTypesByOrderTypeOrderTypeIdGet$Params } from '../fn/mission-types/mission-types-by-order-type-order-type-id-get';
import { missionTypesGet } from '../fn/mission-types/mission-types-get';
import { MissionTypesGet$Params } from '../fn/mission-types/mission-types-get';
import { missionTypesIdDelete } from '../fn/mission-types/mission-types-id-delete';
import { MissionTypesIdDelete$Params } from '../fn/mission-types/mission-types-id-delete';
import { missionTypesIdGet } from '../fn/mission-types/mission-types-id-get';
import { MissionTypesIdGet$Params } from '../fn/mission-types/mission-types-id-get';
import { missionTypesIdPut } from '../fn/mission-types/mission-types-id-put';
import { MissionTypesIdPut$Params } from '../fn/mission-types/mission-types-id-put';
import { missionTypesIdUnarchivePost } from '../fn/mission-types/mission-types-id-unarchive-post';
import { MissionTypesIdUnarchivePost$Params } from '../fn/mission-types/mission-types-id-unarchive-post';
import { missionTypesPost } from '../fn/mission-types/mission-types-post';
import { MissionTypesPost$Params } from '../fn/mission-types/mission-types-post';

@Injectable({ providedIn: 'root' })
export class MissionTypesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `missionTypesGet()` */
  static readonly MissionTypesGetPath = '/mission-types';

  /**
   * Récupérer la liste des types de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesGet$Response(params?: MissionTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionTypeListOutputListResponse>> {
    return missionTypesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des types de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesGet(params?: MissionTypesGet$Params, context?: HttpContext): Observable<MissionTypeListOutputListResponse> {
    return this.missionTypesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionTypeListOutputListResponse>): MissionTypeListOutputListResponse => r.body)
    );
  }

  /** Path part for operation `missionTypesPost()` */
  static readonly MissionTypesPostPath = '/mission-types';

  /**
   * Créer un nouveau type de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionTypesPost$Response(params?: MissionTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionTypeOutput>> {
    return missionTypesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau type de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionTypesPost(params?: MissionTypesPost$Params, context?: HttpContext): Observable<MissionTypeOutput> {
    return this.missionTypesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionTypeOutput>): MissionTypeOutput => r.body)
    );
  }

  /** Path part for operation `missionTypesIdGet()` */
  static readonly MissionTypesIdGetPath = '/mission-types/{id}';

  /**
   * Récupérer les détails d'un type de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesIdGet$Response(params: MissionTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionTypeOutput>> {
    return missionTypesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'un type de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesIdGet(params: MissionTypesIdGet$Params, context?: HttpContext): Observable<MissionTypeOutput> {
    return this.missionTypesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionTypeOutput>): MissionTypeOutput => r.body)
    );
  }

  /** Path part for operation `missionTypesIdPut()` */
  static readonly MissionTypesIdPutPath = '/mission-types/{id}';

  /**
   * Mettre à jour un type de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionTypesIdPut$Response(params: MissionTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionTypeOutput>> {
    return missionTypesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un type de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  missionTypesIdPut(params: MissionTypesIdPut$Params, context?: HttpContext): Observable<MissionTypeOutput> {
    return this.missionTypesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<MissionTypeOutput>): MissionTypeOutput => r.body)
    );
  }

  /** Path part for operation `missionTypesIdDelete()` */
  static readonly MissionTypesIdDeletePath = '/mission-types/{id}';

  /**
   * Supprimer un type de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesIdDelete$Response(params: MissionTypesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return missionTypesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un type de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesIdDelete(params: MissionTypesIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.missionTypesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `missionTypesIdUnarchivePost()` */
  static readonly MissionTypesIdUnarchivePostPath = '/mission-types/{id}/unarchive';

  /**
   * Désarchiver un type de mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesIdUnarchivePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesIdUnarchivePost$Response(params: MissionTypesIdUnarchivePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return missionTypesIdUnarchivePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Désarchiver un type de mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesIdUnarchivePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesIdUnarchivePost(params: MissionTypesIdUnarchivePost$Params, context?: HttpContext): Observable<void> {
    return this.missionTypesIdUnarchivePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `missionTypesByOrderTypeOrderTypeIdGet()` */
  static readonly MissionTypesByOrderTypeOrderTypeIdGetPath = '/mission-types/by-order-type/{orderTypeId}';

  /**
   * Récupérer les types de mission associés à un type de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `missionTypesByOrderTypeOrderTypeIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesByOrderTypeOrderTypeIdGet$Response(params: MissionTypesByOrderTypeOrderTypeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionTypeListOutput>>> {
    return missionTypesByOrderTypeOrderTypeIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les types de mission associés à un type de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `missionTypesByOrderTypeOrderTypeIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  missionTypesByOrderTypeOrderTypeIdGet(params: MissionTypesByOrderTypeOrderTypeIdGet$Params, context?: HttpContext): Observable<Array<MissionTypeListOutput>> {
    return this.missionTypesByOrderTypeOrderTypeIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MissionTypeListOutput>>): Array<MissionTypeListOutput> => r.body)
    );
  }

}
