/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { NotificationOutput } from '../models/notification-output';
import { notificationsIdCountGet } from '../fn/notifications/notifications-id-count-get';
import { NotificationsIdCountGet$Params } from '../fn/notifications/notifications-id-count-get';
import { notificationsNotificationIdDelete } from '../fn/notifications/notifications-notification-id-delete';
import { NotificationsNotificationIdDelete$Params } from '../fn/notifications/notifications-notification-id-delete';
import { notificationsNotificationIdPut } from '../fn/notifications/notifications-notification-id-put';
import { NotificationsNotificationIdPut$Params } from '../fn/notifications/notifications-notification-id-put';
import { notificationsUserIdGet } from '../fn/notifications/notifications-user-id-get';
import { NotificationsUserIdGet$Params } from '../fn/notifications/notifications-user-id-get';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationsIdCountGet()` */
  static readonly NotificationsIdCountGetPath = '/notifications/{id}/count';

  /**
   * Récupère le nombre de notifications non lues et non archivées pour un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsIdCountGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsIdCountGet$Response(params: NotificationsIdCountGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsIdCountGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère le nombre de notifications non lues et non archivées pour un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsIdCountGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsIdCountGet(params: NotificationsIdCountGet$Params, context?: HttpContext): Observable<void> {
    return this.notificationsIdCountGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsUserIdGet()` */
  static readonly NotificationsUserIdGetPath = '/notifications/{userId}';

  /**
   * Récupère les notifications et non archivées pour un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsUserIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsUserIdGet$Response(params: NotificationsUserIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NotificationOutput>>> {
    return notificationsUserIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère les notifications et non archivées pour un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsUserIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsUserIdGet(params: NotificationsUserIdGet$Params, context?: HttpContext): Observable<Array<NotificationOutput>> {
    return this.notificationsUserIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<NotificationOutput>>): Array<NotificationOutput> => r.body)
    );
  }

  /** Path part for operation `notificationsNotificationIdPut()` */
  static readonly NotificationsNotificationIdPutPath = '/notifications/{notificationId}';

  /**
   * Récupère les notifications non lues et non archivées pour un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsNotificationIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsNotificationIdPut$Response(params: NotificationsNotificationIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationOutput>> {
    return notificationsNotificationIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère les notifications non lues et non archivées pour un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsNotificationIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsNotificationIdPut(params: NotificationsNotificationIdPut$Params, context?: HttpContext): Observable<NotificationOutput> {
    return this.notificationsNotificationIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationOutput>): NotificationOutput => r.body)
    );
  }

  /** Path part for operation `notificationsNotificationIdDelete()` */
  static readonly NotificationsNotificationIdDeletePath = '/notifications/{notificationId}';

  /**
   * Archive une notification.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsNotificationIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsNotificationIdDelete$Response(params: NotificationsNotificationIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationOutput>> {
    return notificationsNotificationIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Archive une notification.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsNotificationIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsNotificationIdDelete(params: NotificationsNotificationIdDelete$Params, context?: HttpContext): Observable<NotificationOutput> {
    return this.notificationsNotificationIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationOutput>): NotificationOutput => r.body)
    );
  }

}
