/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OrderTypeListOutputListResponse } from '../models/order-type-list-output-list-response';
import { OrderTypeOutput } from '../models/order-type-output';
import { orderTypesGet } from '../fn/order-types/order-types-get';
import { OrderTypesGet$Params } from '../fn/order-types/order-types-get';
import { orderTypesIdDelete } from '../fn/order-types/order-types-id-delete';
import { OrderTypesIdDelete$Params } from '../fn/order-types/order-types-id-delete';
import { orderTypesIdGet } from '../fn/order-types/order-types-id-get';
import { OrderTypesIdGet$Params } from '../fn/order-types/order-types-id-get';
import { orderTypesIdPut } from '../fn/order-types/order-types-id-put';
import { OrderTypesIdPut$Params } from '../fn/order-types/order-types-id-put';
import { orderTypesIdUnarchivePost } from '../fn/order-types/order-types-id-unarchive-post';
import { OrderTypesIdUnarchivePost$Params } from '../fn/order-types/order-types-id-unarchive-post';
import { orderTypesPost } from '../fn/order-types/order-types-post';
import { OrderTypesPost$Params } from '../fn/order-types/order-types-post';

@Injectable({ providedIn: 'root' })
export class OrderTypesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `orderTypesGet()` */
  static readonly OrderTypesGetPath = '/order-types';

  /**
   * Récupérer la liste des types de commandes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderTypesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesGet$Response(params?: OrderTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTypeListOutputListResponse>> {
    return orderTypesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des types de commandes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderTypesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesGet(params?: OrderTypesGet$Params, context?: HttpContext): Observable<OrderTypeListOutputListResponse> {
    return this.orderTypesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderTypeListOutputListResponse>): OrderTypeListOutputListResponse => r.body)
    );
  }

  /** Path part for operation `orderTypesPost()` */
  static readonly OrderTypesPostPath = '/order-types';

  /**
   * Créer un nouveau type de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderTypesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderTypesPost$Response(params?: OrderTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTypeOutput>> {
    return orderTypesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau type de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderTypesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderTypesPost(params?: OrderTypesPost$Params, context?: HttpContext): Observable<OrderTypeOutput> {
    return this.orderTypesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderTypeOutput>): OrderTypeOutput => r.body)
    );
  }

  /** Path part for operation `orderTypesIdGet()` */
  static readonly OrderTypesIdGetPath = '/order-types/{id}';

  /**
   * Récupérer les détails d'un type de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderTypesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesIdGet$Response(params: OrderTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTypeOutput>> {
    return orderTypesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'un type de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderTypesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesIdGet(params: OrderTypesIdGet$Params, context?: HttpContext): Observable<OrderTypeOutput> {
    return this.orderTypesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderTypeOutput>): OrderTypeOutput => r.body)
    );
  }

  /** Path part for operation `orderTypesIdPut()` */
  static readonly OrderTypesIdPutPath = '/order-types/{id}';

  /**
   * Modifier un type de commande existant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderTypesIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderTypesIdPut$Response(params: OrderTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTypeOutput>> {
    return orderTypesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modifier un type de commande existant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderTypesIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderTypesIdPut(params: OrderTypesIdPut$Params, context?: HttpContext): Observable<OrderTypeOutput> {
    return this.orderTypesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderTypeOutput>): OrderTypeOutput => r.body)
    );
  }

  /** Path part for operation `orderTypesIdDelete()` */
  static readonly OrderTypesIdDeletePath = '/order-types/{id}';

  /**
   * Supprimer un type de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderTypesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesIdDelete$Response(params: OrderTypesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return orderTypesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un type de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderTypesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesIdDelete(params: OrderTypesIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.orderTypesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `orderTypesIdUnarchivePost()` */
  static readonly OrderTypesIdUnarchivePostPath = '/order-types/{id}/unarchive';

  /**
   * Désarchiver un type de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderTypesIdUnarchivePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesIdUnarchivePost$Response(params: OrderTypesIdUnarchivePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return orderTypesIdUnarchivePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Désarchiver un type de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderTypesIdUnarchivePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderTypesIdUnarchivePost(params: OrderTypesIdUnarchivePost$Params, context?: HttpContext): Observable<void> {
    return this.orderTypesIdUnarchivePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
