/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AddressOutputListResponse } from '../models/address-output-list-response';
import { FileInfoResponse } from '../models/file-info-response';
import { OrderAutoCompleteOutput } from '../models/order-auto-complete-output';
import { OrderListOutputListResponse } from '../models/order-list-output-list-response';
import { OrderOutput } from '../models/order-output';
import { OrderOutputListResponse } from '../models/order-output-list-response';
import { ordersAddressesPost } from '../fn/orders/orders-addresses-post';
import { OrdersAddressesPost$Params } from '../fn/orders/orders-addresses-post';
import { ordersAutocompleteGet } from '../fn/orders/orders-autocomplete-get';
import { OrdersAutocompleteGet$Params } from '../fn/orders/orders-autocomplete-get';
import { ordersDatagridClientIdGet } from '../fn/orders/orders-datagrid-client-id-get';
import { OrdersDatagridClientIdGet$Params } from '../fn/orders/orders-datagrid-client-id-get';
import { ordersDatagridPost } from '../fn/orders/orders-datagrid-post';
import { OrdersDatagridPost$Params } from '../fn/orders/orders-datagrid-post';
import { ordersIdUnarchivePost } from '../fn/orders/orders-id-unarchive-post';
import { OrdersIdUnarchivePost$Params } from '../fn/orders/orders-id-unarchive-post';
import { ordersOrderIdDelete } from '../fn/orders/orders-order-id-delete';
import { OrdersOrderIdDelete$Params } from '../fn/orders/orders-order-id-delete';
import { ordersOrderIdFilesFileNameDelete } from '../fn/orders/orders-order-id-files-file-name-delete';
import { OrdersOrderIdFilesFileNameDelete$Params } from '../fn/orders/orders-order-id-files-file-name-delete';
import { ordersOrderIdFilesGet } from '../fn/orders/orders-order-id-files-get';
import { OrdersOrderIdFilesGet$Params } from '../fn/orders/orders-order-id-files-get';
import { ordersOrderIdFilesPost$FormData } from '../fn/orders/orders-order-id-files-post-form-data';
import { OrdersOrderIdFilesPost$FormData$Params } from '../fn/orders/orders-order-id-files-post-form-data';
import { ordersOrderIdFilesPost$Json } from '../fn/orders/orders-order-id-files-post-json';
import { OrdersOrderIdFilesPost$Json$Params } from '../fn/orders/orders-order-id-files-post-json';
import { ordersOrderIdGet } from '../fn/orders/orders-order-id-get';
import { OrdersOrderIdGet$Params } from '../fn/orders/orders-order-id-get';
import { ordersOrderIdPut } from '../fn/orders/orders-order-id-put';
import { OrdersOrderIdPut$Params } from '../fn/orders/orders-order-id-put';
import { ordersPost } from '../fn/orders/orders-post';
import { OrdersPost$Params } from '../fn/orders/orders-post';

@Injectable({ providedIn: 'root' })
export class OrdersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `ordersDatagridPost()` */
  static readonly OrdersDatagridPostPath = '/orders/datagrid';

  /**
   * Récupérer la liste des commandes avec filtre.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersDatagridPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersDatagridPost$Response(params?: OrdersDatagridPost$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderOutputListResponse>> {
    return ordersDatagridPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des commandes avec filtre.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersDatagridPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersDatagridPost(params?: OrdersDatagridPost$Params, context?: HttpContext): Observable<OrderOutputListResponse> {
    return this.ordersDatagridPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderOutputListResponse>): OrderOutputListResponse => r.body)
    );
  }

  /** Path part for operation `ordersAddressesPost()` */
  static readonly OrdersAddressesPostPath = '/orders/addresses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersAddressesPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersAddressesPost$Response(params?: OrdersAddressesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AddressOutputListResponse>> {
    return ordersAddressesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersAddressesPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersAddressesPost(params?: OrdersAddressesPost$Params, context?: HttpContext): Observable<AddressOutputListResponse> {
    return this.ordersAddressesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<AddressOutputListResponse>): AddressOutputListResponse => r.body)
    );
  }

  /** Path part for operation `ordersOrderIdGet()` */
  static readonly OrdersOrderIdGetPath = '/orders/{orderId}';

  /**
   * Récupérer les détails d'une commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdGet$Response(params: OrdersOrderIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderOutput>> {
    return ordersOrderIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'une commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdGet(params: OrdersOrderIdGet$Params, context?: HttpContext): Observable<OrderOutput> {
    return this.ordersOrderIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderOutput>): OrderOutput => r.body)
    );
  }

  /** Path part for operation `ordersOrderIdPut()` */
  static readonly OrdersOrderIdPutPath = '/orders/{orderId}';

  /**
   * Modification d'une commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ordersOrderIdPut$Response(params: OrdersOrderIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderOutput>> {
    return ordersOrderIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modification d'une commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ordersOrderIdPut(params: OrdersOrderIdPut$Params, context?: HttpContext): Observable<OrderOutput> {
    return this.ordersOrderIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderOutput>): OrderOutput => r.body)
    );
  }

  /** Path part for operation `ordersOrderIdDelete()` */
  static readonly OrdersOrderIdDeletePath = '/orders/{orderId}';

  /**
   * Suppression d'une commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdDelete$Response(params: OrdersOrderIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ordersOrderIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Suppression d'une commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdDelete(params: OrdersOrderIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.ordersOrderIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ordersPost()` */
  static readonly OrdersPostPath = '/orders';

  /**
   * Création d'une commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ordersPost$Response(params?: OrdersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return ordersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Création d'une commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ordersPost(params?: OrdersPost$Params, context?: HttpContext): Observable<string> {
    return this.ordersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `ordersAutocompleteGet()` */
  static readonly OrdersAutocompleteGetPath = '/orders/autocomplete';

  /**
   * Méthode de recherche pour l'autocomplétion des commandes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersAutocompleteGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersAutocompleteGet$Response(params?: OrdersAutocompleteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderAutoCompleteOutput>>> {
    return ordersAutocompleteGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Méthode de recherche pour l'autocomplétion des commandes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersAutocompleteGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersAutocompleteGet(params?: OrdersAutocompleteGet$Params, context?: HttpContext): Observable<Array<OrderAutoCompleteOutput>> {
    return this.ordersAutocompleteGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OrderAutoCompleteOutput>>): Array<OrderAutoCompleteOutput> => r.body)
    );
  }

  /** Path part for operation `ordersIdUnarchivePost()` */
  static readonly OrdersIdUnarchivePostPath = '/orders/{id}/unarchive';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersIdUnarchivePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersIdUnarchivePost$Response(params: OrdersIdUnarchivePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ordersIdUnarchivePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersIdUnarchivePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersIdUnarchivePost(params: OrdersIdUnarchivePost$Params, context?: HttpContext): Observable<void> {
    return this.ordersIdUnarchivePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ordersOrderIdFilesGet()` */
  static readonly OrdersOrderIdFilesGetPath = '/orders/{orderId}/files';

  /**
   * Récupère tous les fichiers (documents) d'une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdFilesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdFilesGet$Response(params: OrdersOrderIdFilesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileInfoResponse>>> {
    return ordersOrderIdFilesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère tous les fichiers (documents) d'une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdFilesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdFilesGet(params: OrdersOrderIdFilesGet$Params, context?: HttpContext): Observable<Array<FileInfoResponse>> {
    return this.ordersOrderIdFilesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileInfoResponse>>): Array<FileInfoResponse> => r.body)
    );
  }

  /** Path part for operation `ordersOrderIdFilesPost()` */
  static readonly OrdersOrderIdFilesPostPath = '/orders/{orderId}/files';

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdFilesPost$FormData()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  ordersOrderIdFilesPost$FormData$Response(params: OrdersOrderIdFilesPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
    return ordersOrderIdFilesPost$FormData(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdFilesPost$FormData$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  ordersOrderIdFilesPost$FormData(params: OrdersOrderIdFilesPost$FormData$Params, context?: HttpContext): Observable<FileInfoResponse> {
    return this.ordersOrderIdFilesPost$FormData$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponse>): FileInfoResponse => r.body)
    );
  }

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdFilesPost$Json()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ordersOrderIdFilesPost$Json$Response(params: OrdersOrderIdFilesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
    return ordersOrderIdFilesPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload un fichier/document pour une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdFilesPost$Json$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ordersOrderIdFilesPost$Json(params: OrdersOrderIdFilesPost$Json$Params, context?: HttpContext): Observable<FileInfoResponse> {
    return this.ordersOrderIdFilesPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponse>): FileInfoResponse => r.body)
    );
  }

  /** Path part for operation `ordersOrderIdFilesFileNameDelete()` */
  static readonly OrdersOrderIdFilesFileNameDeletePath = '/orders/{orderId}/files/{fileName}';

  /**
   * Supprime un fichier d'une mission.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersOrderIdFilesFileNameDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdFilesFileNameDelete$Response(params: OrdersOrderIdFilesFileNameDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ordersOrderIdFilesFileNameDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprime un fichier d'une mission.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersOrderIdFilesFileNameDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersOrderIdFilesFileNameDelete(params: OrdersOrderIdFilesFileNameDelete$Params, context?: HttpContext): Observable<void> {
    return this.ordersOrderIdFilesFileNameDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ordersDatagridClientIdGet()` */
  static readonly OrdersDatagridClientIdGetPath = '/orders/datagrid/{clientId}';

  /**
   * Récupère la liste des commandes avec un clientId.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ordersDatagridClientIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersDatagridClientIdGet$Response(params: OrdersDatagridClientIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderListOutputListResponse>> {
    return ordersDatagridClientIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupère la liste des commandes avec un clientId.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ordersDatagridClientIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ordersDatagridClientIdGet(params: OrdersDatagridClientIdGet$Params, context?: HttpContext): Observable<OrderListOutputListResponse> {
    return this.ordersDatagridClientIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderListOutputListResponse>): OrderListOutputListResponse => r.body)
    );
  }

}
