/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { orderStatusGet } from '../fn/order-status/order-status-get';
import { OrderStatusGet$Params } from '../fn/order-status/order-status-get';
import { orderStatusOrderStatusIdDelete } from '../fn/order-status/order-status-order-status-id-delete';
import { OrderStatusOrderStatusIdDelete$Params } from '../fn/order-status/order-status-order-status-id-delete';
import { orderStatusOrderStatusIdGet } from '../fn/order-status/order-status-order-status-id-get';
import { OrderStatusOrderStatusIdGet$Params } from '../fn/order-status/order-status-order-status-id-get';
import { orderStatusOrderStatusIdPut } from '../fn/order-status/order-status-order-status-id-put';
import { OrderStatusOrderStatusIdPut$Params } from '../fn/order-status/order-status-order-status-id-put';
import { OrderStatusOutput } from '../models/order-status-output';
import { orderStatusPost } from '../fn/order-status/order-status-post';
import { OrderStatusPost$Params } from '../fn/order-status/order-status-post';

@Injectable({ providedIn: 'root' })
export class OrderStatusService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `orderStatusGet()` */
  static readonly OrderStatusGetPath = '/order-status';

  /**
   * Récupérer la liste des statuts de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderStatusGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderStatusGet$Response(params?: OrderStatusGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderStatusOutput>>> {
    return orderStatusGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des statuts de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderStatusGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderStatusGet(params?: OrderStatusGet$Params, context?: HttpContext): Observable<Array<OrderStatusOutput>> {
    return this.orderStatusGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OrderStatusOutput>>): Array<OrderStatusOutput> => r.body)
    );
  }

  /** Path part for operation `orderStatusPost()` */
  static readonly OrderStatusPostPath = '/order-status';

  /**
   * Créer un nouveau statut de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderStatusPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderStatusPost$Response(params?: OrderStatusPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return orderStatusPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau statut de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderStatusPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderStatusPost(params?: OrderStatusPost$Params, context?: HttpContext): Observable<string> {
    return this.orderStatusPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `orderStatusOrderStatusIdGet()` */
  static readonly OrderStatusOrderStatusIdGetPath = '/order-status/{orderStatusId}';

  /**
   * Récupérer les détails d’un statut de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderStatusOrderStatusIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderStatusOrderStatusIdGet$Response(params: OrderStatusOrderStatusIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderStatusOutput>> {
    return orderStatusOrderStatusIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d’un statut de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderStatusOrderStatusIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderStatusOrderStatusIdGet(params: OrderStatusOrderStatusIdGet$Params, context?: HttpContext): Observable<OrderStatusOutput> {
    return this.orderStatusOrderStatusIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderStatusOutput>): OrderStatusOutput => r.body)
    );
  }

  /** Path part for operation `orderStatusOrderStatusIdPut()` */
  static readonly OrderStatusOrderStatusIdPutPath = '/order-status/{orderStatusId}';

  /**
   * Modifier un statut de commande existant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderStatusOrderStatusIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderStatusOrderStatusIdPut$Response(params: OrderStatusOrderStatusIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderStatusOutput>> {
    return orderStatusOrderStatusIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modifier un statut de commande existant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderStatusOrderStatusIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderStatusOrderStatusIdPut(params: OrderStatusOrderStatusIdPut$Params, context?: HttpContext): Observable<OrderStatusOutput> {
    return this.orderStatusOrderStatusIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderStatusOutput>): OrderStatusOutput => r.body)
    );
  }

  /** Path part for operation `orderStatusOrderStatusIdDelete()` */
  static readonly OrderStatusOrderStatusIdDeletePath = '/order-status/{orderStatusId}';

  /**
   * Supprimer un statut de commande.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderStatusOrderStatusIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderStatusOrderStatusIdDelete$Response(params: OrderStatusOrderStatusIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return orderStatusOrderStatusIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un statut de commande.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderStatusOrderStatusIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderStatusOrderStatusIdDelete(params: OrderStatusOrderStatusIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.orderStatusOrderStatusIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
