/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { SettingCompanyOutput } from '../models/setting-company-output';
import { SettingCustomizationOutput } from '../models/setting-customization-output';
import { SettingOutput } from '../models/setting-output';
import { SettingPreferenceOutput } from '../models/setting-preference-output';
import { settingsCompanyGet } from '../fn/settings/settings-company-get';
import { SettingsCompanyGet$Params } from '../fn/settings/settings-company-get';
import { settingsCustomizationGet } from '../fn/settings/settings-customization-get';
import { SettingsCustomizationGet$Params } from '../fn/settings/settings-customization-get';
import { settingsGet } from '../fn/settings/settings-get';
import { SettingsGet$Params } from '../fn/settings/settings-get';
import { settingsIdPatch } from '../fn/settings/settings-id-patch';
import { SettingsIdPatch$Params } from '../fn/settings/settings-id-patch';
import { settingsPreferenceGet } from '../fn/settings/settings-preference-get';
import { SettingsPreferenceGet$Params } from '../fn/settings/settings-preference-get';

@Injectable({ providedIn: 'root' })
export class SettingsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `settingsGet()` */
  static readonly SettingsGetPath = '/settings';

  /**
   * Récupérer les paramètres de l'application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsGet$Response(params?: SettingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingOutput>> {
    return settingsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les paramètres de l'application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsGet(params?: SettingsGet$Params, context?: HttpContext): Observable<SettingOutput> {
    return this.settingsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SettingOutput>): SettingOutput => r.body)
    );
  }

  /** Path part for operation `settingsCompanyGet()` */
  static readonly SettingsCompanyGetPath = '/settings/company';

  /**
   * Récupérer les informations de la société.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsCompanyGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsCompanyGet$Response(params?: SettingsCompanyGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingCompanyOutput>> {
    return settingsCompanyGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les informations de la société.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsCompanyGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsCompanyGet(params?: SettingsCompanyGet$Params, context?: HttpContext): Observable<SettingCompanyOutput> {
    return this.settingsCompanyGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SettingCompanyOutput>): SettingCompanyOutput => r.body)
    );
  }

  /** Path part for operation `settingsCustomizationGet()` */
  static readonly SettingsCustomizationGetPath = '/settings/customization';

  /**
   * Récupérer les paramètres de personnalisation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsCustomizationGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsCustomizationGet$Response(params?: SettingsCustomizationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingCustomizationOutput>> {
    return settingsCustomizationGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les paramètres de personnalisation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsCustomizationGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsCustomizationGet(params?: SettingsCustomizationGet$Params, context?: HttpContext): Observable<SettingCustomizationOutput> {
    return this.settingsCustomizationGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SettingCustomizationOutput>): SettingCustomizationOutput => r.body)
    );
  }

  /** Path part for operation `settingsPreferenceGet()` */
  static readonly SettingsPreferenceGetPath = '/settings/preference';

  /**
   * Récupérer les paramètres de personnalisation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsPreferenceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsPreferenceGet$Response(params?: SettingsPreferenceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingPreferenceOutput>> {
    return settingsPreferenceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les paramètres de personnalisation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsPreferenceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsPreferenceGet(params?: SettingsPreferenceGet$Params, context?: HttpContext): Observable<SettingPreferenceOutput> {
    return this.settingsPreferenceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SettingPreferenceOutput>): SettingPreferenceOutput => r.body)
    );
  }

  /** Path part for operation `settingsIdPatch()` */
  static readonly SettingsIdPatchPath = '/settings/{id}';

  /**
   * Mettre à jour les paramètres de l'application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsIdPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  settingsIdPatch$Response(params: SettingsIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingOutput>> {
    return settingsIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour les paramètres de l'application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsIdPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  settingsIdPatch(params: SettingsIdPatch$Params, context?: HttpContext): Observable<SettingOutput> {
    return this.settingsIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<SettingOutput>): SettingOutput => r.body)
    );
  }

}
