/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OperatorOutput } from '../models/operator-output';
import { RoleOutput } from '../models/role-output';
import { UserOutput } from '../models/user-output';
import { UserOutputListResponse } from '../models/user-output-list-response';
import { usersAffectOperatorsPatch } from '../fn/users/users-affect-operators-patch';
import { UsersAffectOperatorsPatch$Params } from '../fn/users/users-affect-operators-patch';
import { usersDatagridPost } from '../fn/users/users-datagrid-post';
import { UsersDatagridPost$Params } from '../fn/users/users-datagrid-post';
import { usersIdDelete } from '../fn/users/users-id-delete';
import { UsersIdDelete$Params } from '../fn/users/users-id-delete';
import { usersIdGet } from '../fn/users/users-id-get';
import { UsersIdGet$Params } from '../fn/users/users-id-get';
import { usersOperatorsGet } from '../fn/users/users-operators-get';
import { UsersOperatorsGet$Params } from '../fn/users/users-operators-get';
import { usersPost } from '../fn/users/users-post';
import { UsersPost$Params } from '../fn/users/users-post';
import { usersProfileGet } from '../fn/users/users-profile-get';
import { UsersProfileGet$Params } from '../fn/users/users-profile-get';
import { usersProfilePut } from '../fn/users/users-profile-put';
import { UsersProfilePut$Params } from '../fn/users/users-profile-put';
import { usersRestaureIdGet } from '../fn/users/users-restaure-id-get';
import { UsersRestaureIdGet$Params } from '../fn/users/users-restaure-id-get';
import { usersRolesGet } from '../fn/users/users-roles-get';
import { UsersRolesGet$Params } from '../fn/users/users-roles-get';
import { usersTagsGet } from '../fn/users/users-tags-get';
import { UsersTagsGet$Params } from '../fn/users/users-tags-get';
import { usersUserIdPut } from '../fn/users/users-user-id-put';
import { UsersUserIdPut$Params } from '../fn/users/users-user-id-put';
import { UserTagOutput } from '../models/user-tag-output';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usersDatagridPost()` */
  static readonly UsersDatagridPostPath = '/users/datagrid';

  /**
   * Récupérer la liste des utilisateurs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersDatagridPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersDatagridPost$Response(params?: UsersDatagridPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutputListResponse>> {
    return usersDatagridPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer la liste des utilisateurs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersDatagridPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersDatagridPost(params?: UsersDatagridPost$Params, context?: HttpContext): Observable<UserOutputListResponse> {
    return this.usersDatagridPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserOutputListResponse>): UserOutputListResponse => r.body)
    );
  }

  /** Path part for operation `usersIdGet()` */
  static readonly UsersIdGetPath = '/users/{id}';

  /**
   * Récupérer les détails d'un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdGet$Response(params: UsersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
    return usersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les détails d'un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdGet(params: UsersIdGet$Params, context?: HttpContext): Observable<UserOutput> {
    return this.usersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserOutput>): UserOutput => r.body)
    );
  }

  /** Path part for operation `usersIdDelete()` */
  static readonly UsersIdDeletePath = '/users/{id}';

  /**
   * Suppression d'un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdDelete$Response(params: UsersIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Suppression d'un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdDelete(params: UsersIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.usersIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersUserIdPut()` */
  static readonly UsersUserIdPutPath = '/users/{userId}';

  /**
   * Modification d'un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersUserIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersUserIdPut$Response(params: UsersUserIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
    return usersUserIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modification d'un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersUserIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersUserIdPut(params: UsersUserIdPut$Params, context?: HttpContext): Observable<UserOutput> {
    return this.usersUserIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserOutput>): UserOutput => r.body)
    );
  }

  /** Path part for operation `usersAffectOperatorsPatch()` */
  static readonly UsersAffectOperatorsPatchPath = '/users/affect-operators';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersAffectOperatorsPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersAffectOperatorsPatch$Response(params?: UsersAffectOperatorsPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return usersAffectOperatorsPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersAffectOperatorsPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersAffectOperatorsPatch(params?: UsersAffectOperatorsPatch$Params, context?: HttpContext): Observable<string> {
    return this.usersAffectOperatorsPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `usersRestaureIdGet()` */
  static readonly UsersRestaureIdGetPath = '/users/restaure/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersRestaureIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersRestaureIdGet$Response(params: UsersRestaureIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersRestaureIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersRestaureIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersRestaureIdGet(params: UsersRestaureIdGet$Params, context?: HttpContext): Observable<void> {
    return this.usersRestaureIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersProfileGet()` */
  static readonly UsersProfileGetPath = '/users/profile';

  /**
   * GET pour obtenir les informations de l'utilisateur connecté (profil).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersProfileGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersProfileGet$Response(params?: UsersProfileGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
    return usersProfileGet(this.http, this.rootUrl, params, context);
  }

  /**
   * GET pour obtenir les informations de l'utilisateur connecté (profil).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersProfileGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersProfileGet(params?: UsersProfileGet$Params, context?: HttpContext): Observable<UserOutput> {
    return this.usersProfileGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserOutput>): UserOutput => r.body)
    );
  }

  /** Path part for operation `usersProfilePut()` */
  static readonly UsersProfilePutPath = '/users/profile';

  /**
   * Modification des informations de l'utilisateur connecté (addresse de livraison, addresse de facturation, etc.).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersProfilePut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersProfilePut$Response(params?: UsersProfilePut$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
    return usersProfilePut(this.http, this.rootUrl, params, context);
  }

  /**
   * Modification des informations de l'utilisateur connecté (addresse de livraison, addresse de facturation, etc.).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersProfilePut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersProfilePut(params?: UsersProfilePut$Params, context?: HttpContext): Observable<UserOutput> {
    return this.usersProfilePut$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserOutput>): UserOutput => r.body)
    );
  }

  /** Path part for operation `usersRolesGet()` */
  static readonly UsersRolesGetPath = '/users/roles';

  /**
   * Récupérer les rôles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersRolesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersRolesGet$Response(params?: UsersRolesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleOutput>>> {
    return usersRolesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les rôles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersRolesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersRolesGet(params?: UsersRolesGet$Params, context?: HttpContext): Observable<Array<RoleOutput>> {
    return this.usersRolesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoleOutput>>): Array<RoleOutput> => r.body)
    );
  }

  /** Path part for operation `usersTagsGet()` */
  static readonly UsersTagsGetPath = '/users/tags';

  /**
   * Récupérer les tags.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersTagsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersTagsGet$Response(params?: UsersTagsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserTagOutput>>> {
    return usersTagsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les tags.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersTagsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersTagsGet(params?: UsersTagsGet$Params, context?: HttpContext): Observable<Array<UserTagOutput>> {
    return this.usersTagsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserTagOutput>>): Array<UserTagOutput> => r.body)
    );
  }

  /** Path part for operation `usersOperatorsGet()` */
  static readonly UsersOperatorsGetPath = '/users/operators';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersOperatorsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersOperatorsGet$Response(params?: UsersOperatorsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperatorOutput>>> {
    return usersOperatorsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersOperatorsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersOperatorsGet(params?: UsersOperatorsGet$Params, context?: HttpContext): Observable<Array<OperatorOutput>> {
    return this.usersOperatorsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OperatorOutput>>): Array<OperatorOutput> => r.body)
    );
  }

  /** Path part for operation `usersPost()` */
  static readonly UsersPostPath = '/users';

  /**
   * Inscription d'un utilisateur.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersPost$Response(params?: UsersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return usersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Inscription d'un utilisateur.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersPost(params?: UsersPost$Params, context?: HttpContext): Observable<string> {
    return this.usersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
