/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { get$Json } from '../fn/versions/get-json';
import { Get$Json$Params } from '../fn/versions/get-json';
import { get$Plain } from '../fn/versions/get-plain';
import { Get$Plain$Params } from '../fn/versions/get-plain';

@Injectable({ providedIn: 'root' })
export class VersionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `get()` */
  static readonly GetPath = '/';

  /**
   * Get the version of the API.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Plain$Response(params?: Get$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return get$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the version of the API.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Plain(params?: Get$Plain$Params, context?: HttpContext): Observable<string> {
    return this.get$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /**
   * Get the version of the API.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Json$Response(params?: Get$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return get$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the version of the API.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Json(params?: Get$Json$Params, context?: HttpContext): Observable<string> {
    return this.get$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
