/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomFormTypeInput } from '../../models/custom-form-type-input';
import { CustomFormTypeOutput } from '../../models/custom-form-type-output';

export interface CustomFormTypesPost$Params {
      body?: CustomFormTypeInput
}

export function customFormTypesPost(http: HttpClient, rootUrl: string, params?: CustomFormTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, customFormTypesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomFormTypeOutput>;
    })
  );
}

customFormTypesPost.PATH = '/custom-form-types';
