/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomFormTypeOutput } from '../../models/custom-form-type-output';

export interface CustomFormTypesGet$Params {
}

export function customFormTypesGet(http: HttpClient, rootUrl: string, params?: CustomFormTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomFormTypeOutput>>> {
  const rb = new RequestBuilder(rootUrl, customFormTypesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomFormTypeOutput>>;
    })
  );
}

customFormTypesGet.PATH = '/custom-form-types';
