/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomFormTypeOutput } from '../../models/custom-form-type-output';

export interface CustomFormTypesIdGet$Params {
  id: string;
}

export function customFormTypesIdGet(http: HttpClient, rootUrl: string, params: CustomFormTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, customFormTypesIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomFormTypeOutput>;
    })
  );
}

customFormTypesIdGet.PATH = '/custom-form-types/{id}';
