/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefreshTokenInput } from '../../models/refresh-token-input';
import { TokenOutput } from '../../models/token-output';

export interface AuthRefreshTokenPost$Params {
      body?: RefreshTokenInput
}

export function authRefreshTokenPost(http: HttpClient, rootUrl: string, params?: AuthRefreshTokenPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenOutput>> {
  const rb = new RequestBuilder(rootUrl, authRefreshTokenPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenOutput>;
    })
  );
}

authRefreshTokenPost.PATH = '/auth/refresh-token';
