/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserInfoOutput } from '../../models/user-info-output';

export interface AuthMeGet$Params {
}

export function authMeGet(http: HttpClient, rootUrl: string, params?: AuthMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfoOutput>> {
  const rb = new RequestBuilder(rootUrl, authMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserInfoOutput>;
    })
  );
}

authMeGet.PATH = '/auth/me';
