/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionDocumentOutput } from '../../models/mission-document-output';

export interface MissionDeleteDocumentMissionIdDocumentIdDelete$Params {
  missionId: string;
  documentId: string;
}

export function missionDeleteDocumentMissionIdDocumentIdDelete(http: HttpClient, rootUrl: string, params: MissionDeleteDocumentMissionIdDocumentIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionDocumentOutput>>> {
  const rb = new RequestBuilder(rootUrl, missionDeleteDocumentMissionIdDocumentIdDelete.PATH, 'delete');
  if (params) {
    rb.path('missionId', params.missionId, {});
    rb.path('documentId', params.documentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MissionDocumentOutput>>;
    })
  );
}

missionDeleteDocumentMissionIdDocumentIdDelete.PATH = '/mission/delete-document/{missionId}/{documentId}';
