/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionInput } from '../../models/mission-input';
import { MissionOutput } from '../../models/mission-output';

export interface MissionIdPut$Params {
  id: string;
      body?: MissionInput
}

export function missionIdPut(http: HttpClient, rootUrl: string, params: MissionIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
  const rb = new RequestBuilder(rootUrl, missionIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionOutput>;
    })
  );
}

missionIdPut.PATH = '/mission/{id}';
