/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionOutput } from '../../models/mission-output';

export interface MissionIdGet$Params {

/**
 * Identifiant unique de la mission
 */
  id: string;
}

export function missionIdGet(http: HttpClient, rootUrl: string, params: MissionIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
  const rb = new RequestBuilder(rootUrl, missionIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionOutput>;
    })
  );
}

missionIdGet.PATH = '/mission/{id}';
