/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MissionUploadImagePost$FormData$Params {
  missionId?: string;
      body?: {
'file'?: Blob;
}
}

export function missionUploadImagePost$FormData(http: HttpClient, rootUrl: string, params?: MissionUploadImagePost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, missionUploadImagePost$FormData.PATH, 'post');
  if (params) {
    rb.query('missionId', params.missionId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

missionUploadImagePost$FormData.PATH = '/mission/upload-image';
