/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionDocumentOutput } from '../../models/mission-document-output';

export interface MissionUploadDocumentsPost$Json$Params {

/**
 * ID of the mission
 */
  missionId?: string;
      body?: {

/**
 * The files to upload
 */
'files'?: Array<Blob>;
}
}

export function missionUploadDocumentsPost$Json(http: HttpClient, rootUrl: string, params?: MissionUploadDocumentsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionDocumentOutput>>> {
  const rb = new RequestBuilder(rootUrl, missionUploadDocumentsPost$Json.PATH, 'post');
  if (params) {
    rb.query('missionId', params.missionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MissionDocumentOutput>>;
    })
  );
}

missionUploadDocumentsPost$Json.PATH = '/mission/upload-documents';
