/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUrlResponse } from '../../models/file-url-response';

export interface FilesSettingsLogoPost$Json$Params {
      body?: {
'file'?: Blob;
}
}

export function filesSettingsLogoPost$Json(http: HttpClient, rootUrl: string, params?: FilesSettingsLogoPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, filesSettingsLogoPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileUrlResponse>;
    })
  );
}

filesSettingsLogoPost$Json.PATH = '/files/settings/logo';
