/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUrlResponse } from '../../models/file-url-response';

export interface FilesUrlFileNameGet$Params {
  fileName: string;
}

export function filesUrlFileNameGet(http: HttpClient, rootUrl: string, params: FilesUrlFileNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, filesUrlFileNameGet.PATH, 'get');
  if (params) {
    rb.path('fileName', params.fileName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileUrlResponse>;
    })
  );
}

filesUrlFileNameGet.PATH = '/files/url/{fileName}';
