/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUrlResponse } from '../../models/file-url-response';

export interface FilesPost$FormData$Params {
  minioFolderName?: string;
  entityId?: string;
      body?: {
'file'?: Blob;
}
}

export function filesPost$FormData(http: HttpClient, rootUrl: string, params?: FilesPost$FormData$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, filesPost$FormData.PATH, 'post');
  if (params) {
    rb.query('minioFolderName', params.minioFolderName, {});
    rb.query('entityId', params.entityId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileUrlResponse>;
    })
  );
}

filesPost$FormData.PATH = '/files';
