/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommandeTypeInput } from '../../models/commande-type-input';
import { CommandeTypeOutput } from '../../models/commande-type-output';

export interface CommandeTypesIdPut$Params {
  id: string;
      body?: CommandeTypeInput
}

export function commandeTypesIdPut(http: HttpClient, rootUrl: string, params: CommandeTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CommandeTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, commandeTypesIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommandeTypeOutput>;
    })
  );
}

commandeTypesIdPut.PATH = '/commande-types/{id}';
