/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommandeAutoCompleteOutput } from '../../models/commande-auto-complete-output';

export interface CommandesAutocompleteGet$Params {
  search?: string;
}

export function commandesAutocompleteGet(http: HttpClient, rootUrl: string, params?: CommandesAutocompleteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommandeAutoCompleteOutput>>> {
  const rb = new RequestBuilder(rootUrl, commandesAutocompleteGet.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommandeAutoCompleteOutput>>;
    })
  );
}

commandesAutocompleteGet.PATH = '/commandes/autocomplete';
