/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderStatusInput } from '../../models/order-status-input';
import { OrderStatusOutput } from '../../models/order-status-output';

export interface OrderStatusOrderStatusIdPut$Params {
  orderStatusId: string;
      body?: OrderStatusInput
}

export function orderStatusOrderStatusIdPut(http: HttpClient, rootUrl: string, params: OrderStatusOrderStatusIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderStatusOutput>> {
  const rb = new RequestBuilder(rootUrl, orderStatusOrderStatusIdPut.PATH, 'put');
  if (params) {
    rb.path('orderStatusId', params.orderStatusId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderStatusOutput>;
    })
  );
}

orderStatusOrderStatusIdPut.PATH = '/order-status/{orderStatusId}';
