/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderStatusOutput } from '../../models/order-status-output';

export interface OrderStatusOrderStatusIdGet$Params {
  orderStatusId: string;
}

export function orderStatusOrderStatusIdGet(http: HttpClient, rootUrl: string, params: OrderStatusOrderStatusIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderStatusOutput>> {
  const rb = new RequestBuilder(rootUrl, orderStatusOrderStatusIdGet.PATH, 'get');
  if (params) {
    rb.path('orderStatusId', params.orderStatusId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderStatusOutput>;
    })
  );
}

orderStatusOrderStatusIdGet.PATH = '/order-status/{orderStatusId}';
