/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderTypeInput } from '../../models/order-type-input';
import { OrderTypeOutput } from '../../models/order-type-output';

export interface OrderTypesPost$Params {
      body?: OrderTypeInput
}

export function orderTypesPost(http: HttpClient, rootUrl: string, params?: OrderTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, orderTypesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderTypeOutput>;
    })
  );
}

orderTypesPost.PATH = '/order-types';
