/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderTypeOutput } from '../../models/order-type-output';

export interface OrderTypesIdGet$Params {
  id: string;
}

export function orderTypesIdGet(http: HttpClient, rootUrl: string, params: OrderTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, orderTypesIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderTypeOutput>;
    })
  );
}

orderTypesIdGet.PATH = '/order-types/{id}';
