/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AffectationTeamLeaderOperatorInput } from '../../models/affectation-team-leader-operator-input';

export interface UsersAffectOperatorsPatch$Params {
      body?: AffectationTeamLeaderOperatorInput
}

export function usersAffectOperatorsPatch(http: HttpClient, rootUrl: string, params?: UsersAffectOperatorsPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, usersAffectOperatorsPatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

usersAffectOperatorsPatch.PATH = '/users/affect-operators';
