/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserTagOutput } from '../../models/user-tag-output';

export interface UsersTagsGet$Params {
  role?: string;
  date?: string;
  dateTo?: string;
}

export function usersTagsGet(http: HttpClient, rootUrl: string, params?: UsersTagsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserTagOutput>>> {
  const rb = new RequestBuilder(rootUrl, usersTagsGet.PATH, 'get');
  if (params) {
    rb.query('role', params.role, {});
    rb.query('date', params.date, {});
    rb.query('dateTo', params.dateTo, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserTagOutput>>;
    })
  );
}

usersTagsGet.PATH = '/users/tags';
