/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserOutput } from '../../models/user-output';

export interface UsersProfileGet$Params {
}

export function usersProfileGet(http: HttpClient, rootUrl: string, params?: UsersProfileGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
  const rb = new RequestBuilder(rootUrl, usersProfileGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserOutput>;
    })
  );
}

usersProfileGet.PATH = '/users/profile';
