/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleOutput } from '../../models/role-output';

export interface UsersRolesGet$Params {
}

export function usersRolesGet(http: HttpClient, rootUrl: string, params?: UsersRolesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleOutput>>> {
  const rb = new RequestBuilder(rootUrl, usersRolesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleOutput>>;
    })
  );
}

usersRolesGet.PATH = '/users/roles';
