/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProfileInput } from '../../models/profile-input';
import { UserOutput } from '../../models/user-output';

export interface UsersProfilePut$Params {
      body?: ProfileInput
}

export function usersProfilePut(http: HttpClient, rootUrl: string, params?: UsersProfilePut$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
  const rb = new RequestBuilder(rootUrl, usersProfilePut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserOutput>;
    })
  );
}

usersProfilePut.PATH = '/users/profile';
