/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientAutoCompleteOutput } from '../../models/client-auto-complete-output';

export interface ClientsAutocompleteGet$Params {
  search?: string;
}

export function clientsAutocompleteGet(http: HttpClient, rootUrl: string, params?: ClientsAutocompleteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientAutoCompleteOutput>>> {
  const rb = new RequestBuilder(rootUrl, clientsAutocompleteGet.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClientAutoCompleteOutput>>;
    })
  );
}

clientsAutocompleteGet.PATH = '/clients/autocomplete';
