/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientInput } from '../../models/client-input';
import { ClientOutput } from '../../models/client-output';

export interface ClientsIdPut$Params {
  id: string;
      body?: ClientInput
}

export function clientsIdPut(http: HttpClient, rootUrl: string, params: ClientsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientOutput>> {
  const rb = new RequestBuilder(rootUrl, clientsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientOutput>;
    })
  );
}

clientsIdPut.PATH = '/clients/{id}';
