/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AbsenceTypeInput } from '../../models/absence-type-input';
import { AbsenceTypeOutput } from '../../models/absence-type-output';

export interface AbsenceTypesPost$Params {
      body?: AbsenceTypeInput
}

export function absenceTypesPost(http: HttpClient, rootUrl: string, params?: AbsenceTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenceTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, absenceTypesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AbsenceTypeOutput>;
    })
  );
}

absenceTypesPost.PATH = '/absence-types';
