/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AbsenceTypeInput } from '../../models/absence-type-input';
import { AbsenceTypeOutput } from '../../models/absence-type-output';

export interface AbsenceTypesIdPut$Params {

/**
 * Identifiant du type d'absence
 */
  id: string;
  
    /**
     * Nouvelles données du type d'absence
     */
    body?: AbsenceTypeInput
}

export function absenceTypesIdPut(http: HttpClient, rootUrl: string, params: AbsenceTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenceTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, absenceTypesIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AbsenceTypeOutput>;
    })
  );
}

absenceTypesIdPut.PATH = '/absence-types/{id}';
