/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommandeStatusOutput } from '../../models/commande-status-output';

export interface CommandeStatusIdGet$Params {
  id: string;
}

export function commandeStatusIdGet(http: HttpClient, rootUrl: string, params: CommandeStatusIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CommandeStatusOutput>> {
  const rb = new RequestBuilder(rootUrl, commandeStatusIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommandeStatusOutput>;
    })
  );
}

commandeStatusIdGet.PATH = '/commande-status/{id}';
