/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddressInput } from '../../models/address-input';
import { CoordinatesMinimal } from '../../models/coordinates-minimal';

export interface AddressesLocalizeAddressPost$Params {
      body?: AddressInput
}

export function addressesLocalizeAddressPost(http: HttpClient, rootUrl: string, params?: AddressesLocalizeAddressPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CoordinatesMinimal>> {
  const rb = new RequestBuilder(rootUrl, addressesLocalizeAddressPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CoordinatesMinimal>;
    })
  );
}

addressesLocalizeAddressPost.PATH = '/addresses/localize-address';
