/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAbsenceInput } from '../../models/user-absence-input';
import { UserAbsenceOutput } from '../../models/user-absence-output';

export interface UserAbsencesUserIdPut$Params {

/**
 * Identifiant de l'absence à mettre à jour
 */
  userId: string;
  
    /**
     * Nouvelles données de l'absence
     */
    body?: UserAbsenceInput
}

export function userAbsencesUserIdPut(http: HttpClient, rootUrl: string, params: UserAbsencesUserIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAbsenceOutput>> {
  const rb = new RequestBuilder(rootUrl, userAbsencesUserIdPut.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAbsenceOutput>;
    })
  );
}

userAbsencesUserIdPut.PATH = '/user-absences/{userId}';
