/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionTypeInput } from '../../models/mission-type-input';
import { MissionTypeOutput } from '../../models/mission-type-output';

export interface MissionTypesIdPut$Params {
  id: string;
      body?: MissionTypeInput
}

export function missionTypesIdPut(http: HttpClient, rootUrl: string, params: MissionTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, missionTypesIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionTypeOutput>;
    })
  );
}

missionTypesIdPut.PATH = '/mission-types/{id}';
