/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionTypeOutput } from '../../models/mission-type-output';

export interface MissionTypesIdGet$Params {
  id: string;
}

export function missionTypesIdGet(http: HttpClient, rootUrl: string, params: MissionTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, missionTypesIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionTypeOutput>;
    })
  );
}

missionTypesIdGet.PATH = '/mission-types/{id}';
