/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionTypeListOutput } from '../../models/mission-type-list-output';

export interface MissionTypesByOrderTypeOrderTypeIdGet$Params {
  orderTypeId: string;
}

export function missionTypesByOrderTypeOrderTypeIdGet(http: HttpClient, rootUrl: string, params: MissionTypesByOrderTypeOrderTypeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionTypeListOutput>>> {
  const rb = new RequestBuilder(rootUrl, missionTypesByOrderTypeOrderTypeIdGet.PATH, 'get');
  if (params) {
    rb.path('orderTypeId', params.orderTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MissionTypeListOutput>>;
    })
  );
}

missionTypesByOrderTypeOrderTypeIdGet.PATH = '/mission-types/by-order-type/{orderTypeId}';
