/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomFormInput } from '../../models/custom-form-input';
import { CustomFormOutput } from '../../models/custom-form-output';

export interface CustomFormPost$Params {
      body?: CustomFormInput
}

export function customFormPost(http: HttpClient, rootUrl: string, params?: CustomFormPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomFormOutput>> {
  const rb = new RequestBuilder(rootUrl, customFormPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomFormOutput>;
    })
  );
}

customFormPost.PATH = '/custom-form';
