/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderOutput } from '../../models/order-output';

export interface OrdersOrderIdGet$Params {
  orderId: string;
}

export function ordersOrderIdGet(http: HttpClient, rootUrl: string, params: OrdersOrderIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderOutput>> {
  const rb = new RequestBuilder(rootUrl, ordersOrderIdGet.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderOutput>;
    })
  );
}

ordersOrderIdGet.PATH = '/orders/{orderId}';
