/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileInfoResponse } from '../../models/file-info-response';

export interface OrdersOrderIdFilesPost$Json$Params {
  orderId: string;
      body?: {
'file'?: Blob;
}
}

export function ordersOrderIdFilesPost$Json(http: HttpClient, rootUrl: string, params: OrdersOrderIdFilesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponse>> {
  const rb = new RequestBuilder(rootUrl, ordersOrderIdFilesPost$Json.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileInfoResponse>;
    })
  );
}

ordersOrderIdFilesPost$Json.PATH = '/orders/{orderId}/files';
