/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileInfoResponse } from '../../models/file-info-response';

export interface OrdersOrderIdFilesGet$Params {
  orderId: string;
}

export function ordersOrderIdFilesGet(http: HttpClient, rootUrl: string, params: OrdersOrderIdFilesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileInfoResponse>>> {
  const rb = new RequestBuilder(rootUrl, ordersOrderIdFilesGet.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FileInfoResponse>>;
    })
  );
}

ordersOrderIdFilesGet.PATH = '/orders/{orderId}/files';
