/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AbsenceTypeOutput } from '../../models/absence-type-output';

export interface AbsenceTypeIdGet$Params {

/**
 * Identifiant du type d'absence
 */
  id: string;
}

export function absenceTypeIdGet(http: HttpClient, rootUrl: string, params: AbsenceTypeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenceTypeOutput>> {
  const rb = new RequestBuilder(rootUrl, absenceTypeIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AbsenceTypeOutput>;
    })
  );
}

absenceTypeIdGet.PATH = '/absence-type/{id}';
