/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionOutput } from '../../models/mission-output';

export interface MissionsAssignPut$Params {
  missionId?: string;
  teamleaderId?: string;
  dateFrom?: string;
  orderIndex?: number;
}

export function missionsAssignPut(http: HttpClient, rootUrl: string, params?: MissionsAssignPut$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionOutput>> {
  const rb = new RequestBuilder(rootUrl, missionsAssignPut.PATH, 'put');
  if (params) {
    rb.query('missionId', params.missionId, {});
    rb.query('teamleaderId', params.teamleaderId, {});
    rb.query('dateFrom', params.dateFrom, {});
    rb.query('orderIndex', params.orderIndex, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionOutput>;
    })
  );
}

missionsAssignPut.PATH = '/missions/assign';
