/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MissionsReArrangPut$Params {
  affectationId?: string;
  orderIndex?: number;
}

export function missionsReArrangPut(http: HttpClient, rootUrl: string, params?: MissionsReArrangPut$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, missionsReArrangPut.PATH, 'put');
  if (params) {
    rb.query('affectationId', params.affectationId, {});
    rb.query('orderIndex', params.orderIndex, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

missionsReArrangPut.PATH = '/missions/re-arrang';
