/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MissionsMissionIdPicturesFileNameDelete$Params {
  missionId: string;
  fileName: string;
}

export function missionsMissionIdPicturesFileNameDelete(http: HttpClient, rootUrl: string, params: MissionsMissionIdPicturesFileNameDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, missionsMissionIdPicturesFileNameDelete.PATH, 'delete');
  if (params) {
    rb.path('missionId', params.missionId, {});
    rb.path('fileName', params.fileName, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

missionsMissionIdPicturesFileNameDelete.PATH = '/missions/{missionId}/pictures/{fileName}';
