/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionListOutputListResponse } from '../../models/mission-list-output-list-response';

export interface MissionsDatagridGet$Params {
  orderId?: string;
  userId?: string;

/**
 * The max number of records.
 */
  '$top'?: Number;

/**
 * The number of records to skip.
 */
  '$skip'?: Number;

/**
 * A function that must evaluate to true for a record to be returned.
 */
  '$filter'?: String;

/**
 * Determines what values are used to order a collection of records.
 */
  '$orderby'?: String;

/**
 * A function that must evaluate to true for a record to be returned.
 */
  '$search'?: String;
}

export function missionsDatagridGet(http: HttpClient, rootUrl: string, params?: MissionsDatagridGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionListOutputListResponse>> {
  const rb = new RequestBuilder(rootUrl, missionsDatagridGet.PATH, 'get');
  if (params) {
    rb.query('orderId', params.orderId, {});
    rb.query('userId', params.userId, {});
    rb.query('$top', params['$top'], {});
    rb.query('$skip', params['$skip'], {});
    rb.query('$filter', params['$filter'], {});
    rb.query('$orderby', params['$orderby'], {});
    rb.query('$search', params['$search'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionListOutputListResponse>;
    })
  );
}

missionsDatagridGet.PATH = '/missions/datagrid';
