/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionStatusInput } from '../../models/mission-status-input';
import { MissionStatusOutput } from '../../models/mission-status-output';

export interface MissionStatusPost$Params {
      body?: MissionStatusInput
}

export function missionStatusPost(http: HttpClient, rootUrl: string, params?: MissionStatusPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionStatusOutput>> {
  const rb = new RequestBuilder(rootUrl, missionStatusPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionStatusOutput>;
    })
  );
}

missionStatusPost.PATH = '/mission-status';
