/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionStatusOutput } from '../../models/mission-status-output';

export interface MissionStatusIdGet$Params {
  id: string;
}

export function missionStatusIdGet(http: HttpClient, rootUrl: string, params: MissionStatusIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionStatusOutput>> {
  const rb = new RequestBuilder(rootUrl, missionStatusIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionStatusOutput>;
    })
  );
}

missionStatusIdGet.PATH = '/mission-status/{id}';
