/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionStatusOutput } from '../../models/mission-status-output';

export interface MissionStatusGet$Params {
}

export function missionStatusGet(http: HttpClient, rootUrl: string, params?: MissionStatusGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissionStatusOutput>>> {
  const rb = new RequestBuilder(rootUrl, missionStatusGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MissionStatusOutput>>;
    })
  );
}

missionStatusGet.PATH = '/mission-status';
