/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AbsenceTypeInput {
  color?: string | null;
  icon?: string | null;
  id?: string;
  name?: string | null;
}
