/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {
  additionalInfo?: string | null;
  city?: string | null;
  country?: string | null;
  createdAt?: string;
  id?: string;
  latitude?: number | null;
  longitude?: number | null;
  postalCode?: string | null;
  street?: string | null;
  updatedAt?: string | null;
}
