/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressOutput } from '../models/address-output';
export interface AddressOutputListResponse {
  count?: number;
  value?: Array<AddressOutput> | null;
}
