/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressInput {
  additionalInfo?: string | null;
  city: string | null;
  country: string | null;
  id?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  postalCode: string | null;
  street: string | null;
}
