/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserOutput } from '../models/user-output';
export interface AffectationMissionXTeamLeaderOutput {
  assignedAt?: string;
  id?: string;
  isHidden?: boolean;
  missionId?: string;
  orderIndex?: number;
  teamLeader?: UserOutput;
  teamLeaderId?: string | null;
}
