/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressOutput } from '../models/address-output';
export interface ClientOutput {
  address: AddressOutput;
  archivedAt?: string | null;
  company: string;
  contactName: string | null;
  email: string;
  groupIds: Array<string>;
  id: string;
  phoneNumber: string;
  roleIds: Array<string>;
}
