/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressInput } from '../models/address-input';
export interface ClientInput {
  address: AddressInput;
  archivedAt?: string | null;
  company: string | null;
  contactName: string | null;
  email: string | null;
  id?: string;
  phoneNumber: string | null;
}
