/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientListOutput } from '../models/client-list-output';
export interface ClientListOutputListResponse {
  count?: number;
  value?: Array<ClientListOutput> | null;
}
