/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomFormListOutput } from '../models/custom-form-list-output';
export interface CustomFormListOutputListResponse {
  count?: number;
  value?: Array<CustomFormListOutput> | null;
}
