/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomFormData } from '../models/custom-form-data';
import { FormStructureOutput } from '../models/form-structure-output';
export interface CustomFormWithBaseAnswerOutput {
  archivedAt?: string | null;
  color: string | null;
  customFormData?: CustomFormData;
  disclaimer?: string | null;
  exportFileName?: string | null;
  exportFileUrl?: string | null;
  formStructure?: FormStructureOutput;
  icon: string | null;
  id: string;
  missionTypeId: string | null;
  missionTypeName?: string | null;
  name: string | null;
}
