/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormStructure } from '../models/form-structure';
export interface CustomFormOutput {
  archivedAt?: string | null;
  color: string | null;
  exportFileName?: string | null;
  exportFileUrl?: string | null;
  formStructure?: FormStructure;
  icon: string | null;
  id: string;
  missionTypeId: string | null;
  missionTypeName?: string | null;
  name: string | null;
}
