/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormStructureInput } from '../models/form-structure-input';
export interface CustomFormInput {
  color: string;
  icon: string;
  missionTypeId?: string | null;
  name: string;
  structure?: FormStructureInput;
}
