/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomFormData } from '../models/custom-form-data';
export interface CustomFormResponseInput {
  customFormId: string;
  data: CustomFormData;
}
