/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleOutput } from '../models/role-output';
import { UserAbsenceOutput } from '../models/user-absence-output';
export interface EmployeeOutput {
  createdAt?: string | null;
  email?: string | null;
  firstname?: string | null;
  id?: string;
  lastname?: string | null;
  phoneNumber?: string | null;
  roles?: Array<RoleOutput> | null;
  userAbsences?: Array<UserAbsenceOutput> | null;
}
