/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldType } from '../models/field-type';
import { OptionOutput } from '../models/option-output';
export interface FieldOutput {
  description?: string | null;
  id: string | null;
  isDeleted: boolean;
  isReadonly: boolean;
  isRequired: boolean;
  label: string | null;
  options?: Array<OptionOutput> | null;
  order: number;
  type: FieldType;
}
