/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FieldType {
  Text = 'Text',
  Paragraph = 'Paragraph',
  Number = 'Number',
  NumberInt = 'NumberInt',
  Date = 'Date',
  DateRange = 'DateRange',
  Datetime = 'Datetime',
  Time = 'Time',
  Radio = 'Radio',
  Checkbox = 'Checkbox',
  Select = 'Select',
  Signature = 'Signature',
  Photo = 'Photo',
  PhotoMultiple = 'PhotoMultiple'
}

export const FieldTypeDefinition = {
  "Text": {
    "color": "#A16826",
    "icon": "text"
  },
  "Paragraph": {
    "color": "#A16826",
    "icon": "contexte"
  },
  "Number": {
    "color": "#2670A1",
    "icon": "numerique"
  },
  "NumberInt": {
    "color": "#2670A1",
    "icon": "chiffre"
  },
  "Date": {
    "color": "#26A168",
    "icon": "date"
  },
  "DateRange": {
    "color": "#26A168",
    "icon": "date"
  },
  "Datetime": {
    "color": "#26A168",
    "icon": "date_heure"
  },
  "Time": {
    "color": "#26A168",
    "icon": "heure"
  },
  "Radio": {
    "color": "#FF8800",
    "icon": "radiobtn"
  },
  "Checkbox": {
    "color": "#FF8800",
    "icon": "checkbox"
  },
  "Select": {
    "color": "#32EBD1",
    "icon": "deroulante"
  },
  "Signature": {
    "color": "#D29E48",
    "icon": "signature"
  },
  "Photo": {
    "color": "#0C4B75",
    "icon": "photo"
  },
  "PhotoMultiple": {
    "color": "#0C4B75",
    "icon": "photo"
  }
}