/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldType } from '../models/field-type';
import { OptionInput } from '../models/option-input';
export interface FieldInput {
  id?: string | null;
  isDeleted: boolean;
  isReadOnly: boolean;
  isRequired: boolean;
  label: string | null;
  options?: Array<OptionInput> | null;
  order: number;
  type: FieldType;
}
