/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SectionOutput } from '../models/section-output';
export interface FormStructureOutput {
  sections: Array<SectionOutput> | null;
}
