/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SectionInput } from '../models/section-input';
export interface FormStructureInput {
  sections?: Array<SectionInput> | null;
}
