/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Section } from '../models/section';
export interface FormStructure {
  sections: Array<Section> | null;
}
