/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionTypeListOutput {
  color?: string | null;
  customFormsCount?: number;
  icon?: string | null;
  id: string;
  name?: string | null;
  position?: number;
}
