/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressInput } from '../models/address-input';
import { CustomFormResponseInput } from '../models/custom-form-response-input';
import { FileUrlResponse } from '../models/file-url-response';
export interface MissionInput {
  address?: AddressInput;
  comments?: string | null;
  customFormResponses?: Array<CustomFormResponseInput> | null;
  dateFrom: string;
  dateTo: string;
  documents?: Array<FileUrlResponse> | null;
  internalComments?: string | null;
  name: string;
  orderId?: string | null;
  photos?: Array<FileUrlResponse> | null;
  statusId: string;
  teamLeaderId?: string | null;
  typeId: string;
}
