/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MissionDocumentType } from '../models/mission-document-type';
export interface MissionDocumentOutput {
  createdAt?: string;
  fileName?: string | null;
  id?: string;
  missionId?: string;
  type?: MissionDocumentType;
  url?: string | null;
}
