/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionAffectationVisibilityDto {
  isHidden: boolean;
  missionAffectationId: string;
}
