/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressOutput } from '../models/address-output';
import { AffectationMissionXTeamLeaderOutput } from '../models/affectation-mission-x-team-leader-output';
import { ClientOutput } from '../models/client-output';
import { CustomFormWithSavedDataOutput } from '../models/custom-form-with-saved-data-output';
import { FileInfoResponse } from '../models/file-info-response';
import { MissionDocumentOutput } from '../models/mission-document-output';
import { MissionStatusOutput } from '../models/mission-status-output';
import { MissionTypeOutput } from '../models/mission-type-output';
import { UserOutput } from '../models/user-output';
export interface MissionOutput {
  address?: AddressOutput;
  affectationMissionXTeamLeaders?: Array<AffectationMissionXTeamLeaderOutput> | null;
  archivedAt?: string | null;
  assignedAt?: string | null;
  client?: ClientOutput;
  comments?: string | null;
  customFormResponses?: Array<CustomFormWithSavedDataOutput> | null;
  dateFrom?: string | null;
  dateTo?: string | null;
  displayId?: string | null;
  documents?: Array<MissionDocumentOutput> | null;
  id?: string;
  internalComments?: string | null;
  isHidden?: boolean;
  name?: string | null;
  orderId?: string | null;
  photos?: Array<FileInfoResponse> | null;
  status?: MissionStatusOutput;
  teamLeader?: UserOutput;
  type?: MissionTypeOutput;
}
