/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionDocumentType {
  archivedAt?: string | null;
  color?: string | null;
  createdAt?: string;
  icon?: string | null;
  id?: string;
  name?: string | null;
  updatedAt?: string | null;
}
