/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MissionListOutput } from '../models/mission-list-output';
export interface MissionListOutputListResponse {
  count?: number;
  value?: Array<MissionListOutput> | null;
}
