/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MissionStatusInput {
  color?: string | null;
  icon?: string | null;
  name?: string | null;
  position?: number;
}
