/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomFormInput } from '../models/custom-form-input';
export interface MissionTypeInput {
  color?: string | null;
  customForms?: Array<CustomFormInput> | null;
  icon?: string | null;
  name?: string | null;
  orderTypeId?: string | null;
  position?: number;
}
