/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MissionTypeListOutput } from '../models/mission-type-list-output';
export interface MissionTypeListOutputListResponse {
  count?: number;
  value?: Array<MissionTypeListOutput> | null;
}
