/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomFormListOutput } from '../models/custom-form-list-output';
export interface MissionTypeOutput {
  archivedAt?: string | null;
  color?: string | null;
  customForms?: Array<CustomFormListOutput> | null;
  icon?: string | null;
  id: string;
  name?: string | null;
  position?: number;
}
