/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationOutput {
  createdAt: string;
  id: string;
  message: string | null;
  seenAt?: string | null;
  targetLink: string | null;
  title: string | null;
}
