/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OperatorOutput {
  dateFrom?: string;
  dateTo?: string | null;
  fullName?: string | null;
  isDefault?: boolean;
  userId?: string;
}
