/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Option {
  id: string | null;
  isDeleted: boolean;
  label: string | null;
  order: number;
}
