/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderListOutput } from '../models/order-list-output';
export interface OrderListOutputListResponse {
  count?: number;
  value?: Array<OrderListOutput> | null;
}
