/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderOutput } from '../models/order-output';
export interface OrderOutputListResponse {
  count?: number;
  value?: Array<OrderOutput> | null;
}
