/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressInput } from '../models/address-input';
export interface OrderInput {
  address: AddressInput;
  archivedAt?: string | null;
  clientId: string;
  comment: string | null;
  id?: string | null;
  name: string;
  statusId: string;
  typeId: string;
}
