/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderStatusOutput } from '../models/order-status-output';
export interface OrderListOutput {
  clientName: string | null;
  displayId: string | null;
  id: string;
  missionIds?: Array<string> | null;
  postalCode?: string | null;
  progression?: string | null;
  status: OrderStatusOutput;
}
