/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MissionTypeListOutput } from '../models/mission-type-list-output';
export interface OrderTypeOutput {
  archivedAt?: string | null;
  color?: string | null;
  icon?: string | null;
  id: string;
  missionTypes?: Array<MissionTypeListOutput> | null;
  name?: string | null;
  position?: number;
}
