/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressOutput } from '../models/address-output';
import { ClientOutput } from '../models/client-output';
import { MissionInfoOutput } from '../models/mission-info-output';
import { OrderStatusOutput } from '../models/order-status-output';
import { OrderTypeOutput } from '../models/order-type-output';
export interface OrderOutput {
  address: AddressOutput;
  archivedAt?: string | null;
  client: ClientOutput;
  comments?: string | null;
  displayId?: string | null;
  id: string;
  missionsInfos?: Array<MissionInfoOutput> | null;
  name: string | null;
  status: OrderStatusOutput;
  type: OrderTypeOutput;
}
