/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderTypeListOutput {
  color?: string | null;
  icon?: string | null;
  id: string;
  missionTypesCount?: number;
  name?: string | null;
  position?: number;
}
