/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderTypeListOutput } from '../models/order-type-list-output';
export interface OrderTypeListOutputListResponse {
  count?: number;
  value?: Array<OrderTypeListOutput> | null;
}
