/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileInput {
  color?: string | null;
  email: string;
  firstname: string | null;
  lastname: string;
  phoneNumber: string;
}
