/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordInput {
  email: string;
  newPassword: string;
  newPasswordConfirmation: string;
  token: string;
}
