/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldResponse } from '../models/field-response';
export interface SectionResponse {
  fields?: Array<FieldResponse> | null;
  sectionId?: string | null;
}
