/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldInput } from '../models/field-input';
export interface SectionInput {
  fields?: Array<FieldInput> | null;
  id?: string | null;
  name: string | null;
}
