/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Field } from '../models/field';
export interface Section {
  fields: Array<Field> | null;
  id: string | null;
  name: string | null;
}
