/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldOutput } from '../models/field-output';
export interface SectionOutput {
  fields: Array<FieldOutput> | null;
  id: string | null;
}
