/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface SettingCustomizationOutput {
  applicationFlavicon?: string | null;
  applicationLogo?: string | null;
  applicationName?: string | null;
  id: string;
  operatorStartAddress?: Address;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  tertiaryColor?: string | null;
}
