/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingPreferenceOutput {
  defaultPlanningMode?: string | null;
  grayOutFinishedMissions?: boolean | null;
  id?: string;
  missionAsAppointment?: boolean | null;
  showWeekendsInPlanning?: boolean | null;
}
