/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressInput } from '../models/address-input';
export interface SettingInput {
  apeCode?: string | null;
  applicationFlavicon?: string | null;
  applicationLogo?: string | null;
  applicationName?: string | null;
  billingAddress?: AddressInput;
  companyName?: string | null;
  defaultPlanningMode?: string | null;
  email?: string | null;
  fax?: string | null;
  grayOutFinishedMissions?: boolean | null;
  id?: string;
  legalForm?: string | null;
  missionAsAppointment?: boolean | null;
  operatorStartAddress?: AddressInput;
  phone?: string | null;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  showWeekendsInPlanning?: boolean | null;
  sirenNumber?: string | null;
  tertiaryColor?: string | null;
  url?: string | null;
}
