/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingOutput {
  applicationFlavicon?: string | null;
  applicationLogo?: string | null;
  applicationName?: string | null;
  defaultPlanningMode?: string | null;
  grayOutFinishedMissions?: boolean;
  id: string;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  showWeekendsInPlanning?: boolean;
  tertiaryColor?: string | null;
}
