/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserAbsenceOutput } from '../models/user-absence-output';
export interface UserAbsenceOutputListResponse {
  count?: number;
  value?: Array<UserAbsenceOutput> | null;
}
