/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbsenceTypeOutput } from '../models/absence-type-output';
export interface UserAbsenceOutput {
  comments?: string | null;
  endDate?: string | null;
  startDate?: string | null;
  type?: AbsenceTypeOutput;
}
