/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserOutput } from '../models/user-output';
export interface UserOutputListResponse {
  count?: number;
  value?: Array<UserOutput> | null;
}
