/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInput {
  affectedToTeamleaderId?: string | null;
  archivedAt?: string | null;
  color?: string | null;
  email: string;
  firstname: string | null;
  id?: string | null;
  lastname: string;
  roleIds: Array<string>;
}
