/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserAbsenceInput {
  comments?: string | null;
  endDate?: string | null;
  startDate?: string | null;
  typeId?: string;
  userId?: string;
}
