/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OperatorOutput } from '../models/operator-output';
export interface UserTagOutput {
  affectedOperators?: Array<OperatorOutput> | null;
  color?: string | null;
  firstname?: string | null;
  id?: string;
  lastname?: string | null;
  trigram?: string | null;
}
