/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleOutput } from '../models/role-output';
export interface UserOutput {
  affectedToTeamleader?: UserOutput;
  archivedAt?: string | null;
  color?: string | null;
  email?: string | null;
  firstname?: string | null;
  id?: string;
  lastname?: string | null;
  roles?: Array<RoleOutput> | null;
}
