/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInfoOutput {
  email?: string | null;
  fullName?: string | null;
  id?: string;
  role?: string | null;
}
