/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AbsenceTypesService } from './services/absence-types.service';
import { AddressesService } from './services/addresses.service';
import { AuthService } from './services/auth.service';
import { BogusService } from './services/bogus.service';
import { ClientsService } from './services/clients.service';
import { CustomFormsService } from './services/custom-forms.service';
import { EmployeesService } from './services/employees.service';
import { FilesService } from './services/files.service';
import { MissionsService } from './services/missions.service';
import { MissionStatusesService } from './services/mission-statuses.service';
import { MissionTypesService } from './services/mission-types.service';
import { NotificationsService } from './services/notifications.service';
import { OrdersService } from './services/orders.service';
import { OrderStatusService } from './services/order-status.service';
import { OrderTypesService } from './services/order-types.service';
import { SettingsService } from './services/settings.service';
import { UserAbsencesService } from './services/user-absences.service';
import { UsersService } from './services/users.service';
import { VersionsService } from './services/versions.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AbsenceTypesService,
    AddressesService,
    AuthService,
    BogusService,
    ClientsService,
    CustomFormsService,
    EmployeesService,
    FilesService,
    MissionsService,
    MissionStatusesService,
    MissionTypesService,
    NotificationsService,
    OrdersService,
    OrderStatusService,
    OrderTypesService,
    SettingsService,
    UserAbsencesService,
    UsersService,
    VersionsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
