/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AbsenceTypesService } from './services/absence-types.service';
export { AddressesService } from './services/addresses.service';
export { AuthService } from './services/auth.service';
export { BogusService } from './services/bogus.service';
export { ClientsService } from './services/clients.service';
export { CustomFormsService } from './services/custom-forms.service';
export { EmployeesService } from './services/employees.service';
export { FilesService } from './services/files.service';
export { MissionsService } from './services/missions.service';
export { MissionStatusesService } from './services/mission-statuses.service';
export { MissionTypesService } from './services/mission-types.service';
export { NotificationsService } from './services/notifications.service';
export { OrdersService } from './services/orders.service';
export { OrderStatusService } from './services/order-status.service';
export { OrderTypesService } from './services/order-types.service';
export { SettingsService } from './services/settings.service';
export { UserAbsencesService } from './services/user-absences.service';
export { UsersService } from './services/users.service';
export { VersionsService } from './services/versions.service';
