/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingOutput } from '../../models/setting-output';

export interface SettingsGet$Params {
}

export function settingsGet(http: HttpClient, rootUrl: string, params?: SettingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingOutput>> {
  const rb = new RequestBuilder(rootUrl, settingsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingOutput>;
    })
  );
}

settingsGet.PATH = '/settings';
