/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingCompanyOutput } from '../../models/setting-company-output';

export interface SettingsCompanyGet$Params {
}

export function settingsCompanyGet(http: HttpClient, rootUrl: string, params?: SettingsCompanyGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingCompanyOutput>> {
  const rb = new RequestBuilder(rootUrl, settingsCompanyGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingCompanyOutput>;
    })
  );
}

settingsCompanyGet.PATH = '/settings/company';
