/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingInput } from '../../models/setting-input';
import { SettingOutput } from '../../models/setting-output';

export interface SettingsIdPatch$Params {
  id: string;
      body?: SettingInput
}

export function settingsIdPatch(http: HttpClient, rootUrl: string, params: SettingsIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingOutput>> {
  const rb = new RequestBuilder(rootUrl, settingsIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingOutput>;
    })
  );
}

settingsIdPatch.PATH = '/settings/{id}';
